import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type, apikey, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Cache-Control":"no-store"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}});
const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max);
const OWNER_EMAILS=new Set(["perkdropofficial@gmail.com"]);
const slugify=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
const cityLabel=(s:string)=>({adelaide:"Adelaide",sydney:"Sydney",melbourne:"Melbourne",brisbane:"Brisbane",perth:"Perth",darwin:"Darwin",canberra:"Canberra",hobart:"Hobart","gold-coast":"Gold Coast"} as Record<string,string>)[s]||s;
const cityZone=(s:string)=>({adelaide:'Australia/Adelaide',sydney:'Australia/Sydney',melbourne:'Australia/Melbourne',brisbane:'Australia/Brisbane',perth:'Australia/Perth',darwin:'Australia/Darwin',canberra:'Australia/Sydney',hobart:'Australia/Hobart','gold-coast':'Australia/Brisbane'} as Record<string,string>)[String(s||'').toLowerCase()]||'Australia/Sydney';
const timingFor=(starts:string|null,ends:string|null,city:string)=>{if(!starts||!ends)return 'Check availability';try{const f=new Intl.DateTimeFormat('en-AU',{timeZone:cityZone(city),weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});return `${f.format(new Date(starts))} – ${f.format(new Date(ends))}`}catch{return 'Check availability'}};
const nextDropId=async(service:any)=>{const year=new Date().getUTCFullYear(),prefix=`PD-${year}-`;const {data}=await service.from('catalogue_items').select('id').like('id',`${prefix}%`).order('id',{ascending:false}).limit(1);const last=String(data?.[0]?.id||'').split('-').pop()||'0';return `${prefix}${String(Number(last)+1).padStart(4,'0')}`};

Deno.serve(async(req)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
  if(!['GET','POST'].includes(req.method))return json({ok:false,error:'method_not_allowed'},405);
  try{
    const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const auth=req.headers.get('authorization')||'',token=auth.toLowerCase().startsWith('bearer ')?auth.slice(7).trim():'';if(!token)return json({ok:false,error:'unauthorized'},401);
    const {data:userData,error:userError}=await service.auth.getUser(token);const user=userData.user;if(userError||!user||!OWNER_EMAILS.has(String(user.email||'').toLowerCase()))return json({ok:false,error:'admin_required'},403);
    const queue=async(eventType:string,merchantId:string|null,recipient:string,payload:any={})=>{if(!recipient)return;try{await service.from('merchant_notification_outbox').insert({merchant_id:merchantId,event_type:eventType,recipient_email:recipient,payload})}catch{}};
    const userEmail=async(userId:string|null)=>{if(!userId)return '';try{const {data}=await service.auth.admin.getUserById(userId);return String(data.user?.email||'').toLowerCase()}catch{return ''}};

    if(req.method==='GET'){
      const [claims,offers,submissions,campaigns,terms,profileChanges,ownership,notifications,merchants,redemptions,ledger,demand]=await Promise.all([
        service.from('merchant_claims').select('*,merchants:merchant_id(id,name,slug,listing_status,partner_tier)').order('created_at',{ascending:false}).limit(200),
        service.from('merchant_offers').select('*,merchants:merchant_id(id,name,slug,listing_status,partner_tier)').in('status',['pending','active','paused','rejected']).order('created_at',{ascending:false}).limit(300),
        service.from('merchant_submissions').select('id,merchant_id,merchant_offer_id,status,business_name,contact_name,contact_email,offer_title,category,city,state,created_at').order('created_at',{ascending:false}).limit(200),
        service.from('featured_campaigns').select('*,merchants:merchant_id(name,slug)').order('created_at',{ascending:false}).limit(200),
        service.from('merchant_commercial_terms').select('*,merchants:merchant_id(name,slug)').order('created_at',{ascending:false}).limit(200),
        service.from('merchant_profile_change_requests').select('*,merchants:merchant_id(name,slug,primary_location,primary_city,primary_state)').order('created_at',{ascending:false}).limit(200),
        service.from('merchant_ownership_requests').select('*,merchants:merchant_id(name,slug,listing_status)').order('created_at',{ascending:false}).limit(200),
        service.from('merchant_notification_outbox').select('id,merchant_id,event_type,recipient_email,status,attempt_count,last_error,created_at,sent_at').order('created_at',{ascending:false}).limit(200),
        service.from('merchants').select('id,name,slug,listing_status,partner_tier,primary_city,primary_state,business_group_id,verified_at,created_at,updated_at').order('name').limit(1000),
        service.from('redemptions').select('id,merchant_id,merchant_offer_id,status,party_size,gross_value,discount_value,commission_value,created_at,redeemed_at,expires_at').order('created_at',{ascending:false}).limit(5000),
        service.from('commission_ledger').select('id,merchant_id,redemption_id,entry_type,gross_value,perkdrop_value,merchant_value,currency,status,occurred_at,paid_at').order('occurred_at',{ascending:false}).limit(5000),
        service.from('demand_signals').select('city,vertical,drop_type,inventory_unit,quantity,status,expires_at,created_at').eq('status','open').gt('expires_at',new Date().toISOString()).limit(2000)
      ]);
      return json({ok:true,claims:claims.data||[],offers:offers.data||[],submissions:submissions.data||[],featured_campaigns:campaigns.data||[],commercial_terms:terms.data||[],profile_changes:profileChanges.data||[],ownership_requests:ownership.data||[],notifications:notifications.data||[],merchants:merchants.data||[],redemptions:redemptions.data||[],ledger:ledger.data||[],demand:demand.data||[]});
    }

    const body=await req.json().catch(()=>null) as any;if(!body||typeof body!=='object')return json({ok:false,error:'invalid_body'},400);const action=clean(body.action,80);

    if(action==='claim_approve'){
      const claimId=clean(body.claim_id,80);const {data:claim}=await service.from('merchant_claims').select('*,merchants:merchant_id(name)').eq('id',claimId).eq('status','pending').maybeSingle();if(!claim)return json({ok:false,error:'claim_not_found'},404);
      const {error:memberError}=claim.user_id?await service.from('merchant_members').upsert({merchant_id:claim.merchant_id,user_id:claim.user_id,role:'owner',status:'active'},{onConflict:'merchant_id,user_id'}):{error:null};if(memberError)return json({ok:false,error:'membership_create_failed'},500);
      await Promise.all([service.from('merchant_claims').update({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by:user.email}).eq('id',claim.id),service.from('merchants').update({listing_status:'verified',claimable:false,verified_at:new Date().toISOString()}).eq('id',claim.merchant_id)]);
      await queue('claim_approved',claim.merchant_id,claim.contact_email,{claim_id:claim.id,merchant_name:claim.merchants?.name||''});return json({ok:true,status:'approved',membership_created:Boolean(claim.user_id)});
    }
    if(action==='claim_reject'){
      const claimId=clean(body.claim_id,80),reason=clean(body.reason,1000)||'We could not verify this claim with the information supplied.';const {data,error}=await service.from('merchant_claims').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:user.email,metadata:{reason}}).eq('id',claimId).eq('status','pending').select('merchant_id,contact_email').maybeSingle();if(error||!data)return json({ok:false,error:'claim_reject_failed'},409);const {count}=await service.from('merchant_claims').select('id',{count:'exact',head:true}).eq('merchant_id',data.merchant_id).eq('status','pending');if(!count)await service.from('merchants').update({listing_status:'unclaimed',claimable:true}).eq('id',data.merchant_id).eq('listing_status','claim_pending');await queue('claim_rejected',data.merchant_id,data.contact_email,{claim_id:claimId,reason});return json({ok:true,status:'rejected'});
    }
    if(action==='profile_change_approve'){
      const requestId=clean(body.request_id,80);const {data:r}=await service.from('merchant_profile_change_requests').select('*').eq('id',requestId).eq('status','pending').maybeSingle();if(!r)return json({ok:false,error:'profile_change_not_found'},404);const patch:any={};for(const k of ['name','primary_location','primary_city','primary_state'])if(r.requested_patch?.[k]!==undefined)patch[k]=r.requested_patch[k];if(!Object.keys(patch).length)return json({ok:false,error:'empty_profile_change'},409);const {error}=await service.from('merchants').update(patch).eq('id',r.merchant_id);if(error)return json({ok:false,error:'profile_change_apply_failed'},500);await service.from('merchant_profile_change_requests').update({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by:user.email,review_notes:clean(body.reason,1000)||null}).eq('id',requestId);await queue('profile_change_approved',r.merchant_id,await userEmail(r.user_id),{request_id:requestId,patch});return json({ok:true,status:'approved'});
    }
    if(action==='profile_change_reject'){
      const requestId=clean(body.request_id,80),reason=clean(body.reason,1000)||'The requested profile change could not be verified.';const {data,error}=await service.from('merchant_profile_change_requests').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:user.email,review_notes:reason}).eq('id',requestId).eq('status','pending').select('merchant_id,user_id').maybeSingle();if(error||!data)return json({ok:false,error:'profile_change_reject_failed'},409);await queue('profile_change_rejected',data.merchant_id,await userEmail(data.user_id),{request_id:requestId,reason});return json({ok:true,status:'rejected'});
    }
    if(action==='ownership_reviewing'){
      const requestId=clean(body.request_id,80);const {data,error}=await service.from('merchant_ownership_requests').update({status:'reviewing',admin_notes:clean(body.reason,1500)||null,reviewed_by:user.email}).eq('id',requestId).eq('status','pending').select('*').maybeSingle();if(error||!data)return json({ok:false,error:'ownership_request_not_found'},404);await queue('ownership_request_reviewing',data.merchant_id,data.contact_email,{request_id:requestId});return json({ok:true,status:'reviewing'});
    }
    if(action==='ownership_transfer_approve'){
      const requestId=clean(body.request_id,80);const {data:r}=await service.from('merchant_ownership_requests').select('*').eq('id',requestId).in('status',['pending','reviewing']).eq('request_type','transfer').maybeSingle();if(!r)return json({ok:false,error:'transfer_request_not_found'},404);await service.from('merchant_members').update({status:'inactive'}).eq('merchant_id',r.merchant_id).neq('user_id',r.user_id);const {error:memberError}=await service.from('merchant_members').upsert({merchant_id:r.merchant_id,user_id:r.user_id,role:'owner',status:'active'},{onConflict:'merchant_id,user_id'});if(memberError)return json({ok:false,error:'transfer_membership_failed'},500);await Promise.all([service.from('merchant_ownership_requests').update({status:'approved',admin_notes:clean(body.reason,1500)||'Ownership transfer approved after review.',reviewed_at:new Date().toISOString(),reviewed_by:user.email}).eq('id',requestId),service.from('merchants').update({listing_status:'verified',claimable:false,verified_at:new Date().toISOString()}).eq('id',r.merchant_id)]);await queue('ownership_transfer_approved',r.merchant_id,r.contact_email,{request_id:requestId});return json({ok:true,status:'approved'});
    }
    if(action==='ownership_resolve'||action==='ownership_reject'){
      const requestId=clean(body.request_id,80),newStatus=action==='ownership_reject'?'rejected':'resolved',reason=clean(body.reason,1500)||null;const {data,error}=await service.from('merchant_ownership_requests').update({status:newStatus,admin_notes:reason,reviewed_at:new Date().toISOString(),reviewed_by:user.email}).eq('id',requestId).in('status',['pending','reviewing']).select('*').maybeSingle();if(error||!data)return json({ok:false,error:'ownership_update_failed'},409);await queue(newStatus==='rejected'?'ownership_request_rejected':'ownership_request_resolved',data.merchant_id,data.contact_email,{request_id:requestId,reason});return json({ok:true,status:newStatus});
    }
    if(action==='offer_publish'){
      const offerId=clean(body.offer_id,80);const {data:offer}=await service.from('merchant_offers').select('*,merchants:merchant_id(id,name,listing_status,partner_tier,partner_since,hero_image_url,primary_location,primary_city,primary_state,latitude,longitude,cuisine,venue_type,website_url)').eq('id',offerId).eq('status','pending').maybeSingle();if(!offer)return json({ok:false,error:'offer_not_pending'},404);const merchant=offer.merchants;if(!merchant)return json({ok:false,error:'merchant_missing'},409);if(!offer.capacity_total||Number(offer.capacity_total)<1)return json({ok:false,error:'capacity_required_before_publish'},409);if(offer.capacity_remaining===null)await service.from('merchant_offers').update({capacity_remaining:Number(offer.capacity_total)}).eq('id',offer.id);
      const id=await nextDropId(service),slug=`${id.toLowerCase()}-${slugify(offer.title)}`,detailUrl=`/deals/${slug}`;const price=offer.discount_type==='free'?'FREE':offer.deal_price!==null?`$${Number(offer.deal_price).toFixed(Number(offer.deal_price)%1?2:0)}`:offer.discount_percent!==null?`${Number(offer.discount_percent)}% OFF`:'DROP';const image=offer.media_url||merchant.hero_image_url||null;if(!image)return json({ok:false,error:'media_required_before_publish'},409);
      const city=clean(offer.city,100)||merchant.primary_city||'adelaide',state=clean(offer.state,80)||merchant.primary_state||'SA',location=clean(offer.location,400)||merchant.primary_location||'';if(!location)return json({ok:false,error:'location_required_before_publish'},409);const externalSource=offer.booking_url||offer.affiliate_url||merchant.website_url||'',source=externalSource||`https://perkdrop.au${detailUrl}`;
      const {error:dropError}=await service.from('catalogue_items').insert({id,merchant_id:offer.merchant_id,merchant:merchant.name,title:offer.title,description:offer.description,category:offer.category||'Experiences',kind:'deal',city,state,location,timing:timingFor(offer.starts_at,offer.ends_at,city),end_date:offer.ends_at?new Date(offer.ends_at).toISOString().slice(0,10):null,price,conditions:offer.conditions||'Claim the Drop through PerkDrop and follow the business conditions shown.',booking:true,source,verified:new Date().toISOString().slice(0,10),hot:false,featured:Boolean(offer.featured),slug,detail_url:detailUrl,city_label:cityLabel(city),active:true,metadata:{original_go_url:externalSource,merchant_offer_id:offer.id,submitted_by_merchant:true,perkdrop_redemption:true,venue_timezone:cityZone(city)},latitude:Number.isFinite(Number(offer.latitude))?Number(offer.latitude):merchant.latitude,longitude:Number.isFinite(Number(offer.longitude))?Number(offer.longitude):merchant.longitude,image_url:image,image_alt:`${merchant.name} — ${offer.title}`,cuisine:offer.cuisine||merchant.cuisine||null,discount_percent:offer.discount_percent,venue_type:offer.venue_type||merchant.venue_type||null,offer_origin:offer.exclusive?'perkdrop_exclusive':offer.affiliate_url?'affiliate':'merchant_submitted',exclusive:Boolean(offer.exclusive),affiliate_url:offer.affiliate_url,affiliate_network:offer.affiliate_network});if(dropError){console.error('publish drop',dropError);return json({ok:false,error:'drop_publish_failed',detail:dropError.message},500)}
      await Promise.all([service.from('merchant_offers').update({status:'active',published_drop_id:id,review_notes:null,capacity_remaining:offer.capacity_remaining===null?Number(offer.capacity_total):offer.capacity_remaining}).eq('id',offer.id),service.from('merchant_submissions').update({status:'approved',published_drop_id:id}).eq('merchant_offer_id',offer.id),service.from('merchants').update({listing_status:offer.exclusive?'partner':merchant.listing_status==='unclaimed'?'verified':merchant.listing_status,partner_tier:offer.exclusive&&merchant.partner_tier==='none'?'performance':merchant.partner_tier,partner_since:offer.exclusive&&!merchant.partner_since?new Date().toISOString():merchant.partner_since}).eq('id',offer.merchant_id)]);
      let recipient=await userEmail(offer.created_by);if(!recipient){const {data:s}=await service.from('merchant_submissions').select('contact_email').eq('merchant_offer_id',offer.id).maybeSingle();recipient=s?.contact_email||''}await queue('drop_approved',offer.merchant_id,recipient,{offer_id:offer.id,published_drop_id:id,detail_url:detailUrl,title:offer.title});return json({ok:true,published_drop_id:id,detail_url:detailUrl,capacity_total:Number(offer.capacity_total)},201);
    }
    if(action==='offer_reject'){
      const offerId=clean(body.offer_id,80),reason=clean(body.reason,1500)||'Not approved for publication.';const {data:offer}=await service.from('merchant_offers').select('merchant_id,created_by,title').eq('id',offerId).eq('status','pending').maybeSingle();if(!offer)return json({ok:false,error:'offer_not_pending'},404);const {data,error}=await service.from('merchant_offers').update({status:'rejected',review_notes:reason}).eq('id',offerId).eq('status','pending').select('id').maybeSingle();if(error||!data)return json({ok:false,error:'offer_reject_failed'},409);await service.from('merchant_submissions').update({status:'rejected',notes_internal:reason}).eq('merchant_offer_id',offerId);let recipient=await userEmail(offer.created_by);if(!recipient){const {data:s}=await service.from('merchant_submissions').select('contact_email').eq('merchant_offer_id',offerId).maybeSingle();recipient=s?.contact_email||''}await queue('drop_rejected',offer.merchant_id,recipient,{offer_id:offerId,title:offer.title,reason});return json({ok:true,status:'rejected'});
    }
    if(action==='commercial_terms_activate'){
      const merchantId=clean(body.merchant_id,80),model=clean(body.model,40);if(!merchantId||!['none','cpa','revenue_share','cpc','subscription','affiliate','hybrid'].includes(model))return json({ok:false,error:'invalid_terms'},400);await service.from('merchant_commercial_terms').update({status:'ended',effective_to:new Date().toISOString()}).eq('merchant_id',merchantId).eq('status','active');const rate=body.commission_rate===null||body.commission_rate===''?null:Number(body.commission_rate),flat=body.commission_flat===null||body.commission_flat===''?null:Number(body.commission_flat),click=body.click_rate===null||body.click_rate===''?null:Number(body.click_rate),monthly=body.monthly_fee===null||body.monthly_fee===''?null:Number(body.monthly_fee);if(rate!==null&&(!Number.isFinite(rate)||rate<0||rate>1))return json({ok:false,error:'commission_rate_must_be_decimal_0_to_1'},400);const {data,error}=await service.from('merchant_commercial_terms').insert({merchant_id:merchantId,model,commission_flat:Number.isFinite(flat)?flat:null,commission_rate:Number.isFinite(rate)?rate:null,click_rate:Number.isFinite(click)?click:null,monthly_fee:Number.isFinite(monthly)?monthly:null,currency:'AUD',affiliate_network:clean(body.affiliate_network,120)||null,affiliate_program_id:clean(body.affiliate_program_id,160)||null,referral_tag:clean(body.referral_tag,160)||null,terms_url:clean(body.terms_url,1200)||null,status:'active',effective_from:new Date().toISOString(),metadata:{activated_by:user.email}}).select('*').single();if(error)return json({ok:false,error:'terms_activate_failed'},500);if(model!=='none')await service.from('merchants').update({listing_status:'partner',partner_tier:model==='subscription'?'featured':'performance',partner_since:new Date().toISOString()}).eq('id',merchantId);return json({ok:true,terms:data},201);
    }
    if(action==='featured_activate'){
      const campaignId=clean(body.campaign_id,80);const {data,error}=await service.from('featured_campaigns').update({status:'active'}).eq('id',campaignId).in('status',['draft','scheduled','paused']).select('*').maybeSingle();if(error||!data)return json({ok:false,error:'campaign_activate_failed'},409);if(data.catalogue_item_id)await service.from('catalogue_items').update({featured:true}).eq('id',data.catalogue_item_id);if(data.merchant_offer_id)await service.from('merchant_offers').update({featured:true}).eq('id',data.merchant_offer_id);return json({ok:true,campaign:data});
    }
    return json({ok:false,error:'unknown_action'},400);
  }catch(e){console.error('perkdrop-admin-commercial',e);return json({ok:false,error:'admin_commercial_failed'},500)}
});
