import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const UPDATED='30 August 2026';
const VERSION='2026-08-30-v1';
const BASE='https://khzpdyyywiucfhubxkev.supabase.co/functions/v1/perkdrop-legal';
const CONTACT='perkdropofficial@gmail.com';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const nav=`<nav><a href="${BASE}?doc=terms">Terms</a><a href="${BASE}?doc=privacy">Privacy</a><a href="${BASE}?doc=merchant-terms">Merchant Terms</a><a href="${BASE}?doc=drop-terms">Drop Terms</a><a href="${BASE}?doc=verification">Verification</a><a href="${BASE}?doc=affiliate">Affiliate Disclosure</a></nav>`;
const docs:Record<string,{title:string,sub:string,body:string}>={
terms:{title:'Terms of Use',sub:'Rules for using PerkDrop, discovering offers and claiming capacity-limited Drops.',body:`
<h2>1. About PerkDrop</h2><p>PerkDrop is an Australian discovery and reservation platform for deals, food and drink offers, events, experiences and other promotions. Unless PerkDrop expressly says otherwise, the underlying goods, food, services, event or experience are supplied by the relevant business, venue, organiser or other third party, not by PerkDrop.</p>
<h2>2. Listings and offer information</h2><p>We try to present useful and current information, but offers, prices, opening hours, availability and third-party conditions can change. Check the details shown in the Drop and any official business or offer source before travelling, booking or paying. If there is a material conflict between a merchant-created Drop and the merchant's clearly stated conditions, contact PerkDrop so it can be reviewed.</p>
<h2>3. What PerkDrop labels mean</h2><ul><li><strong>Offer checked / Source checked:</strong> PerkDrop checked the source or offer information at or around the date shown. It does not mean the business has claimed the listing.</li><li><strong>Verified Business:</strong> PerkDrop has reviewed evidence that a person controlling the PerkDrop business profile is authorised to act for the business. It is not an endorsement, quality guarantee or safety certification.</li><li><strong>PerkDrop Partner:</strong> the business has an active commercial or promotional relationship with PerkDrop.</li><li><strong>PerkDrop Exclusive:</strong> the offer is represented to PerkDrop as an offer available exclusively through PerkDrop for the stated period or conditions.</li></ul>
<h2>4. Capacity-limited Drops</h2><p>Some Drops have limited capacity. Selecting a party size can reduce the remaining capacity by that number of people. A reservation code may expire and may be subject to usage limits. Claiming a Drop is <strong>not automatically a table booking</strong> unless the Drop expressly says that it includes or confirms a booking. If a separate venue booking is required, you must complete it.</p><p>You must not resell codes, fabricate redemptions, circumvent capacity limits, create duplicate claims to deprive others of availability, or otherwise misuse the service.</p>
<h2>5. Third-party links, bookings and payments</h2><p>PerkDrop may link to a business website, booking provider, map, ticketing service, affiliate partner or other third party. Those services have their own terms and privacy practices. PerkDrop is not responsible for operating those third-party services.</p>
<h2>6. Your responsibilities</h2><p>Use PerkDrop lawfully and provide accurate information where you submit information to us. Follow the conditions of any Drop you claim and behave reasonably toward participating businesses and staff.</p>
<h2>7. Australian Consumer Law</h2><p>Nothing in these Terms excludes, restricts or modifies any consumer guarantee, right or remedy that cannot lawfully be excluded under the Australian Consumer Law or other applicable law. Any limitation of PerkDrop's liability in these Terms applies only to the extent permitted by law.</p>
<h2>8. Availability and changes</h2><p>PerkDrop may correct errors, remove expired or misleading listings, suspend misuse, or change service features. We do not promise uninterrupted availability. Material changes to these Terms will apply prospectively from the updated date unless law requires otherwise.</p>
<h2>9. Complaints and corrections</h2><p>Send complaints, corrections or legal enquiries to <a href="mailto:${CONTACT}">${CONTACT}</a>. Include enough information for us to identify the relevant listing, Drop or account.</p>
<h2>10. Governing law</h2><p>These Terms are governed by the laws applying in South Australia, Australia, subject to any rights you have under mandatory laws that apply to you.</p>`},
privacy:{title:'Privacy Policy',sub:'How PerkDrop collects, uses and handles information across the consumer and business services.',body:`
<h2>1. Scope</h2><p>This policy explains PerkDrop's privacy practices. Where the Privacy Act 1988 (Cth) and Australian Privacy Principles apply to PerkDrop, we intend to comply with them. We also use the practices below more generally as our baseline for handling information.</p>
<h2>2. Information we may collect</h2><ul><li>browser/session identifiers used to operate and measure the service;</li><li>app activity such as page views, deal views, saves, directions, shares, claims, bookings or redemptions;</li><li>traffic information such as referral source and UTM campaign information;</li><li>your selected city and device-stored Saved Drops or current redemption information;</li><li>location coordinates when you actively grant browser/device location permission, used for nearby and distance features;</li><li>business account details, names, email addresses, phone numbers, role information and verification evidence;</li><li>business profile, offer, media, conditions, capacity and commercial information supplied by merchants;</li><li>for some public business submissions, a hashed form of the source IP address and user-agent information for abuse prevention and security;</li><li>party size, reservation/redemption code, status, expiry and redemption activity for capacity-limited Drops;</li><li>messages, complaints and other communications with PerkDrop.</li></ul>
<h2>3. Why we use information</h2><p>We use information to provide and improve PerkDrop, show nearby results, save and reserve Drops, prevent misuse, verify business ownership, administer merchant accounts and offers, measure performance, respond to enquiries, maintain security, and meet legal or compliance obligations.</p>
<h2>4. Location</h2><p>Live location is requested only through your device/browser permission flow. If granted, coordinates are used for location-aware features such as distance and nearby sorting. You can deny or revoke location permission in your browser/device settings.</p>
<h2>5. Local device storage</h2><p>PerkDrop may store selected city, Saved Drops, redemption details and a session identifier in browser/device storage so the app works consistently between visits. Clearing site data can remove these locally stored items.</p>
<h2>6. Service providers and disclosures</h2><p>PerkDrop uses service providers to operate the platform, including Supabase for database/authentication/backend functions and Vercel for hosting. We may also use mapping, analytics, communications or transactional-email services and link to external booking or merchant services. Providers may process information in Australia or overseas depending on their infrastructure and contract terms.</p><p>We may disclose information where reasonably necessary to deliver the service, investigate misuse, resolve a merchant ownership dispute, comply with law, or protect users, businesses or PerkDrop. We do not describe PerkDrop as selling personal information.</p>
<h2>7. Direct marketing</h2><p>Where PerkDrop sends commercial electronic messages, we will use an appropriate consent basis, identify the sender and provide a functional unsubscribe method where required. You may opt out of marketing messages without stopping necessary account, security, verification or transaction communications.</p>
<h2>8. Access, correction and complaints</h2><p>To request access to or correction of information we hold about you, or to make a privacy complaint, email <a href="mailto:${CONTACT}">${CONTACT}</a>. We may need to verify your identity before providing account or verification information.</p>
<h2>9. Security and retention</h2><p>We use access controls and server-side systems intended to limit unauthorised access. No online service can promise absolute security. We retain information for as long as reasonably needed for service delivery, fraud prevention, dispute handling, legal obligations and legitimate business records, then delete or de-identify it where appropriate.</p>
<h2>10. Automated decisions</h2><p>PerkDrop does not currently describe a significant automated decision-making system that makes decisions about individuals using their personal information. If that changes materially, we will update this policy and provide information required by applicable law.</p>
<h2>11. Changes</h2><p>We may update this policy as the service changes. The current version and date are shown on this page.</p>`},
'merchant-terms':{title:'Merchant Terms',sub:'Terms for claiming, verifying and managing a business or publishing Drops through PerkDrop.',body:`
<h2>1. Authority</h2><p>By claiming a business or using the merchant tools, you confirm that you are authorised to act for that business or organiser and that the information you provide is accurate and not misleading.</p>
<h2>2. Verification</h2><p>Claiming is not verification. PerkDrop may verify control using one or more reasonable methods, including a business-domain email, official website, ABN or other business details, official social account, phone confirmation, documents, or other evidence. PerkDrop may request further evidence.</p><p>A <strong>Verified Business</strong> badge means PerkDrop has reviewed evidence of authority to control the PerkDrop listing. It is not an endorsement of the business, its food, safety, service or financial position.</p>
<h2>3. Account security</h2><p>You are responsible for protecting your login credentials and for activity performed by authorised users of your merchant account. Contact PerkDrop promptly if control of the business or account changes.</p>
<h2>4. Business profile</h2><p>Merchants may update ordinary profile information such as description, cuisine, venue type, public contact details, website, booking link, social links, opening hours, facilities and approved media. Changes to verified identity details such as the business name or primary address may require PerkDrop review before being applied.</p>
<h2>5. Photos, logos and content</h2><p>You grant PerkDrop a non-exclusive licence to host, reproduce, resize, crop and display content you provide for the purpose of operating and promoting the business, its listing and its Drops. You confirm you have the rights and authority necessary to provide that content. Do not upload material you do not have permission to use.</p>
<h2>6. Merchant Drops</h2><p>Offers must be genuine, accurate and capable of being honoured. You must clearly state material limits such as dates, times, exclusions, minimum spend, booking requirements and capacity. PerkDrop may review, reject, pause, correct or remove offers that appear misleading, unlawful, expired, incorrect or impractical.</p>
<h2>7. Capacity and redemption</h2><p>If you publish a capacity-limited Drop, the capacity you set represents the number of eligible customer spots available under the stated offer. Valid, unexpired PerkDrop redemption codes must be honoured subject to the conditions clearly disclosed in that Drop. Merchants must not falsely mark redemptions or manipulate capacity or performance data.</p>
<h2>8. Your underlying service obligations</h2><p>The merchant remains responsible for the goods and services it provides, including customer service, food safety and allergen information, licences, permits, insurance, pricing, fulfilment and compliance with the Australian Consumer Law and other applicable requirements.</p>
<h2>9. Fees and commercial relationships</h2><p>Claiming or listing may be free where PerkDrop states that it is free. A commission, subscription, affiliate, featured-placement or other fee applies only where separate commercial terms are agreed or clearly accepted. PerkDrop will not retrospectively impose a new charge on completed activity without an agreed basis.</p>
<h2>10. Partner, sponsored and affiliate labels</h2><p>PerkDrop may label a commercial relationship, sponsored placement, affiliate arrangement or exclusive offer so users can understand the relationship. Paying PerkDrop does not itself create a Verified Business badge.</p>
<h2>11. Ownership disputes and transfers</h2><p>PerkDrop may restrict changes or access while an ownership dispute or transfer is reviewed. We may ask parties for evidence and may transfer, suspend or restore control where reasonably satisfied about current authority. Verification may be reviewed or revoked if evidence becomes unreliable.</p>
<h2>12. Suspension and termination</h2><p>PerkDrop may suspend merchant access or remove content for serious or repeated misuse, fraud, misleading offers, security concerns, legal risk or failure to honour valid Drops. Where appropriate, we will give a reason or opportunity to correct an issue.</p>
<h2>13. Changes to these terms</h2><p>Material changes will apply prospectively from the updated date and will not be used to create surprise retrospective charges. Continued use after reasonable notice may constitute acceptance where permitted by law.</p>
<h2>14. Contact</h2><p>Merchant support and disputes: <a href="mailto:${CONTACT}">${CONTACT}</a>.</p>`},
'drop-terms':{title:'Drop & Reservation Terms',sub:'How capacity, party size and redemption codes work.',body:`
<h2>Capacity</h2><p>A capacity-limited Drop has a finite number of customer spots or redemptions. For food-related Drops, selecting a party size may reduce the available diner capacity by that number.</p>
<h2>Reservation codes</h2><p>A successful claim may generate a PerkDrop code. Codes can have expiry times, per-user/session limits or other stated conditions. A code is for the claimant's genuine use and must not be sold, duplicated, fabricated or manipulated.</p>
<h2>Table bookings</h2><p><strong>Claiming a Drop is not a table reservation unless the Drop explicitly says so.</strong> If a venue booking link or separate booking step is shown, complete that step as well. A PerkDrop code does not override a venue's lawful service, safety or booking requirements.</p>
<h2>Merchant conditions</h2><p>The conditions displayed in the Drop apply. Check dates, times, exclusions, minimum spend and other restrictions before travelling or paying. If a condition appears materially inconsistent or misleading, report it to PerkDrop.</p>
<h2>Expiry, sold-out and cancellation</h2><p>Expired or sold-out Drops cannot be newly claimed. PerkDrop may cancel or correct a Drop where the merchant withdraws it, information is materially wrong, fraud is suspected or the offer can no longer lawfully or practically be supplied. Your Australian Consumer Law rights are not excluded.</p>`},
verification:{title:'Business Verification',sub:'What PerkDrop trust labels mean—and what they do not mean.',body:`
<h2>UNCLAIMED</h2><p>The business has not completed PerkDrop ownership verification. Information may be based on public or official sources.</p>
<h2>CLAIM PENDING</h2><p>Someone has submitted a request to control the listing and PerkDrop is reviewing it. The claimant has not yet been approved.</p>
<h2>✓ VERIFIED BUSINESS</h2><p>PerkDrop has reviewed reasonable evidence that the person controlling the PerkDrop profile is authorised to act for the business. Evidence may include a business-domain email, official website, ABN/business details, official social account, phone confirmation, documents or other reasonable proof.</p><p><strong>Verification is not an endorsement, safety certification, review score or guarantee of quality.</strong></p>
<h2>💜 PERKDROP PARTNER</h2><p>The business has an active commercial or promotional relationship with PerkDrop. Partnership does not replace ownership verification and does not guarantee quality.</p>
<h2>🔥 PERKDROP EXCLUSIVE</h2><p>The specific offer is represented to PerkDrop as exclusive to PerkDrop under its stated conditions or period.</p>
<h2>Offer checked vs business verified</h2><p><strong>Offer checked / Source checked</strong> refers to PerkDrop checking offer information or its source. <strong>Verified Business</strong> refers to ownership/control of the PerkDrop listing. They are different checks.</p>
<h2>Review and revocation</h2><p>PerkDrop may re-check, suspend or remove verification where ownership changes, a dispute is raised, evidence becomes unreliable or access appears compromised.</p>`},
affiliate:{title:'Affiliate & Sponsored Disclosure',sub:'How PerkDrop identifies commercial relationships.',body:`
<h2>Commercial relationships</h2><p>PerkDrop may earn revenue from commissions, referrals, affiliate links, sponsored placements, subscriptions or other agreed arrangements with businesses or partners.</p>
<h2>Clear labels</h2><p>Where a commercial relationship is relevant to how an offer or placement appears, PerkDrop aims to label it clearly using wording such as Partner, Sponsored, Affiliate, Featured or another description suited to the arrangement.</p>
<h2>No automatic endorsement</h2><p>A paid, affiliate or partner relationship does not mean PerkDrop guarantees the business, product or service. It also does not automatically mean the business is verified. Verification and commercial status are separate concepts.</p>
<h2>Affiliate actions</h2><p>Where an affiliate arrangement applies, PerkDrop may receive a commission or other benefit if you click, book, buy or complete another eligible action through a tracked link. This generally does not increase the price solely because PerkDrop receives a commission, although the third party controls its own pricing.</p>
<h2>Questions</h2><p>Questions about a commercial label or relationship can be sent to <a href="mailto:${CONTACT}">${CONTACT}</a>.</p>`}
};

function page(doc:string){const d=docs[doc]||docs.terms;return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08090e"><title>${esc(d.title)} | PerkDrop</title><style>*{box-sizing:border-box}body{margin:0;background:#08090e;color:#f5f6f8;font:14px/1.65 Arial,sans-serif}a{color:#cbb9ff}.w{max-width:900px;margin:auto;padding:18px 18px 70px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:25px;font-weight:900;color:#fff;text-decoration:none}.brand span{color:#ff4db8}.back{border:1px solid #303545;border-radius:12px;padding:8px 11px;color:#fff;text-decoration:none}.hero{margin-top:20px;border:1px solid #2d3241;border-radius:22px;padding:24px;background:#0e1018}.hero small{font-weight:900;letter-spacing:1.2px;color:#ff4db8}.hero h1{font-size:clamp(30px,7vw,50px);line-height:1.05;margin:6px 0}.hero p{color:#aeb4c0;margin:0}nav{display:flex;flex-wrap:wrap;gap:7px;margin:16px 0}nav a{border:1px solid #303545;border-radius:999px;padding:7px 10px;text-decoration:none;color:#d8dbe2;font-size:12px;font-weight:700}.body{background:#11131b;border:1px solid #2d3241;border-radius:20px;padding:24px}.body h2{font-size:20px;margin:28px 0 7px}.body h2:first-child{margin-top:0}.body p,.body li{color:#c5c9d2}.body strong{color:#fff}.body ul{padding-left:20px}.foot{text-align:center;color:#777f8e;font-size:11px;margin-top:22px}@media(max-width:600px){.w{padding:12px 12px 55px}.hero,.body{padding:18px}.top{align-items:flex-start}}</style></head><body><main class="w"><div class="top"><a class="brand" href="https://perkdrop.au">Perk<span>Drop</span></a><a class="back" href="https://perkdrop.au">Public app</a></div><section class="hero"><small>PERKDROP LEGAL</small><h1>${esc(d.title)}</h1><p>${esc(d.sub)}</p></section>${nav}<article class="body">${d.body}</article><div class="foot">PerkDrop · Australia · Updated ${UPDATED} · Version ${VERSION} · ${CONTACT}</div></main></body></html>`}
Deno.serve(req=>{const url=new URL(req.url);const doc=url.searchParams.get('doc')||'terms';return new Response(page(doc),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}})});
