import {planSummary,planCalendar} from '../public/outing-rules.mjs';
import {trackAction} from '../public/analytics.mjs';
export default function PlanDetails({plan,catalogue=[]}){
 const items=plan.items.map(item=>({...item,...catalogue.find(d=>d.id===item.id&&(!plan.group_details?.branch_ids?.[item.id]||d.locationId===plan.group_details.branch_ids[item.id]))})),summary=planSummary(items,plan.planned_for,plan.group_details||{}),locations=items.map(d=>Number.isFinite(d.latitude)&&Number.isFinite(d.longitude)?`${d.latitude},${d.longitude}`:d.location).filter(Boolean);
 for(const item of items){if(item.detailUrl)item.href=item.detailUrl;}
 const directions=locations.length?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(locations.at(-1))}${locations.length>1?'&origin='+encodeURIComponent(locations[0]):''}${locations.length>2?'&waypoints='+encodeURIComponent(locations.slice(1,-1).join('|')):''}`:null;
 function calendar(){const blob=new Blob([planCalendar({...plan,items})],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='perkdrop-plan.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);trackAction('calendar_export');}
 return <><p>{summary.unknownPrices?`Known admission: $${summary.knownCost.toFixed(2)} · ${summary.unknownPrices} price${summary.unknownPrices===1?'':'s'} to confirm`:`Listed group admission: $${summary.knownCost.toFixed(2)}`}. Food, transport and extras are separate.</p><ol>{items.map((item,i)=><li key={item.id}>{item.href?<a href={item.href}>{item.merchant} — {item.title}</a>:<span>{item.title}</span>}<p className="muted">{item.available===false?'No longer available':summary.items[i].schedule}<br/>{summary.items[i].cost.label}{item.suitability?.warning&&<><br/>{item.suitability.warning}</>}</p></li>)}</ol>{summary.distanceKm!==null&&items.length>1&&<p className="muted">{summary.distanceKm.toFixed(1)} km between stops in a straight line. Open the route for actual travel times.</p>}<div className="actions">{plan.planned_for&&<button onClick={calendar}>Add to calendar + reminder</button>}{directions&&<a className="action" target="_blank" rel="noopener noreferrer" href={directions}>Route & travel times</a>}</div><p className="muted">This plan is not a reservation. Check current times, prices and each venue’s booking requirements. Your calendar app controls reminder delivery.</p></>;
}
