import Head from 'next/head';
export default function PrivateShell({title,children}){
  return <><Head><title>{title} | PerkDrop</title><meta name="robots" content="noindex,nofollow"/><meta name="referrer" content="no-referrer"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="stylesheet" href="/styles.css?v=marketplace-private-1"/></Head>
    <div className="private-shell"><header><a href="/" className="brand">Perk<span>Drop</span></a><nav aria-label="Your PerkDrop"><a href="/">Find deals</a><a href="/my-perks?tab=saved">Saved & passes</a><a href="/plans">Plans</a><a href="/updates">Updates</a></nav></header><main><h1>{title}</h1>{children}</main></div>
    <style jsx global>{`
      .private-shell{max-width:920px;margin:auto;padding:20px;color:#f8f7fc}.private-shell header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.private-shell nav{display:flex;gap:18px;flex-wrap:wrap}.private-shell main{padding:34px 0 80px}.private-shell h1{font-size:clamp(30px,7vw,48px);line-height:1.15;margin-bottom:20px}.private-shell h2{margin-top:0}.private-shell section{padding:22px;background:#151722;border:1px solid #383c4f;border-radius:18px;margin:18px 0;overflow-wrap:anywhere}.private-shell label{display:grid;gap:8px;margin:15px 0}.private-shell input,.private-shell select,.private-shell textarea{width:100%;min-width:0;padding:12px;border:1px solid #737992;border-radius:8px;background:#0e1018;color:white}.private-shell button,.private-shell .action{display:inline-block;padding:12px 16px;border-radius:10px;background:#ff75bc;color:#170b14;font-weight:700;border:0;cursor:pointer;white-space:normal}.private-shell button:disabled{opacity:.6;cursor:wait}.private-shell a{color:#ff99ce}.private-shell .action{color:#170b14}.private-shell .actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}.private-shell .muted{color:#c1c4d3}.private-shell .status{display:inline-block;border:1px solid #7b809a;padding:5px 10px;border-radius:8px;text-transform:uppercase;font-size:12px;font-weight:800}.private-shell :focus-visible{outline:3px solid #97eeff;outline-offset:4px}.private-shell dl{display:grid;grid-template-columns:minmax(85px,1fr) minmax(0,2fr);gap:12px}.private-shell dd{margin:0}.private-shell .error{color:#ffb2bc}.private-shell .tabs{display:flex;gap:8px;flex-wrap:wrap}.private-shell .tabs button[aria-pressed=false]{background:#303549;color:white}.private-shell .qr{background:white;border-radius:10px;padding:12px;max-width:100%;width:260px;height:auto}.private-shell code{overflow-wrap:anywhere;font-size:22px}.private-shell fieldset{border:1px solid #4a4f65;border-radius:10px;margin:18px 0;padding:10px 14px}.private-shell legend{padding:0 6px;font-weight:700}.private-shell .choice-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:0 14px}.private-shell .choice-grid label{display:block;margin:9px 0}.private-shell .choice-grid input{width:auto;margin-right:7px}.private-shell .section-row{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.private-shell .share-link{margin-top:16px;padding-top:16px;border-top:1px solid #383c4f}.private-shell ol{padding-left:22px}.private-shell li{margin:8px 0}
    `}</style></>;
}
export function privateResponse({res}){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Robots-Tag','noindex, nofollow');res.setHeader('Referrer-Policy','no-referrer');return {props:{}};}
