import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Linking,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {enableNotifications,disableNotifications,notificationStatus} from './notifications';
import {deleteAccount} from './marketplace';
import {clearCatalogueCache} from './catalogue-cache';
import {resetAnalyticsIdentity} from './analytics';
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#08090e'},body:{padding:22,gap:16},title:{color:'#fff',fontSize:25,fontWeight:'800'},text:{color:'#c8c4d3',fontSize:15,lineHeight:23},button:{minHeight:48,padding:15,borderRadius:14,backgroundColor:'#a45cff',justifyContent:'center'},label:{color:'#08090e',fontWeight:'800',fontSize:16,textAlign:'center'},secondary:{minHeight:46,padding:12,justifyContent:'center'},link:{color:'#d6b8ff',fontSize:15,textAlign:'center'},input:{minHeight:50,padding:14,color:'#fff',backgroundColor:'#211e2b',borderRadius:12},row:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{padding:11,borderRadius:20,backgroundColor:'#211e2b'},chosen:{borderWidth:1,borderColor:'#d6b8ff'},error:{color:'#ffb3b3',fontSize:14,lineHeight:21},skeleton:{height:160,borderRadius:18,backgroundColor:'#211e2b',marginBottom:16},card:{padding:18,borderRadius:18,backgroundColor:'#191923',marginBottom:16},danger:{borderWidth:1,borderColor:'#d78696',backgroundColor:'#241820'}});
export class AppErrorBoundary extends React.Component {
  state={failed:false,key:0};
  static getDerivedStateFromError(){return {failed:true};}
  render(){
    if(this.state.failed)return <SafeAreaView style={s.page}><View style={s.body}><Text style={s.title}>Let’s reopen PerkDrop</Text><Text style={s.text}>Something interrupted this screen. Your saved items are not being deleted.</Text><Pressable accessibilityRole="button" style={s.button} onPress={()=>this.setState(x=>({failed:false,key:x.key+1}))}><Text style={s.label}>Try again</Text></Pressable><Pressable style={s.secondary} onPress={()=>Linking.openURL('https://perkdrop.au/contact').catch(()=>{})}><Text style={s.link}>Contact support</Text></Pressable></View></SafeAreaView>;
    return <React.Fragment key={this.state.key}>{this.props.children}</React.Fragment>;
  }
}
export function LoadingCards(){return <View style={s.body} accessibilityRole="progressbar" accessibilityLabel="Loading local listings"><ActivityIndicator/><View style={s.skeleton}/><View style={s.skeleton}/></View>;}
export function WelcomeSheet({visible,onChoose,onNearby,onAdelaide}){
  return <Modal visible={visible} animationType="fade" onRequestClose={onChoose}><SafeAreaView style={s.page}><View style={[s.body,{flex:1,justifyContent:'center'}]}><Text style={s.title}>Good things. Closer to you.</Text><Text style={s.text}>Find events, free activities and local perks. Choose an area first—you can browse without an account or location permission.</Text><Pressable style={s.button} onPress={onChoose}><Text style={s.label}>Choose my suburb</Text></Pressable><Pressable style={s.secondary} onPress={onNearby}><Text style={s.link}>Use my location</Text></Pressable><Pressable style={s.secondary} onPress={onAdelaide}><Text style={s.link}>Explore Adelaide</Text></Pressable><Text style={s.text}>Always check each listing’s dates, conditions and official booking link before heading out.</Text></View></SafeAreaView></Modal>;
}
const cities=[['adelaide','Adelaide','Australia/Adelaide'],['sydney','Sydney','Australia/Sydney'],['melbourne','Melbourne','Australia/Melbourne'],['brisbane','Brisbane','Australia/Brisbane'],['perth','Perth','Australia/Perth'],['hobart','Hobart','Australia/Hobart'],['canberra','Canberra','Australia/Sydney'],['darwin','Darwin','Australia/Darwin']];
export function NotificationControls(){
  const [status,setStatus]=useState(null),[city,setCity]=useState(cities[0]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let live=true;notificationStatus().then(v=>{if(live){setStatus(v);const saved=cities.find(c=>c[0]===v.preferences?.city);if(saved)setCity(saved);}}).catch(()=>{if(live)setError('Notification settings could not be checked.');});return()=>{live=false;};},[]);
  const toggle=async()=>{setBusy(true);setError('');try{setStatus(status?.enabled?await disableNotifications():await enableNotifications({city:city[0],timezone:city[2]}));}catch(e){setError(e.message||'Settings could not be updated.');}finally{setBusy(false);}};
  return <View style={s.card}><Text style={s.title}>Worth a reminder</Text><Text style={s.text}>Optional weekly local picks. Quiet hours are 8 pm–8 am in your selected city. Turn them off here at any time.</Text>{status?.available===false?<Text style={s.text}>Remote alerts are not enabled for this release candidate. The updates below are in-app only.</Text>:<><View style={s.row}>{cities.map(c=><Pressable key={c[0]} disabled={status?.enabled||busy} style={[s.chip,city[0]===c[0]&&s.chosen]} onPress={()=>setCity(c)}><Text style={s.link}>{c[1]}</Text></Pressable>)}</View><Pressable disabled={!status||busy} style={[s.button,(!status||busy)&&{opacity:0.5}]} onPress={toggle}><Text style={s.label}>{busy?'Updating…':status?.enabled?'Turn alerts off':'Enable weekly alerts'}</Text></Pressable></>}{error?<Text style={s.error}>{error}</Text>:null}</View>;
}
export function SettingsSheet({visible,onClose,onDeleted}){
  const [confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const remove=async()=>{
    if(confirmation!=='DELETE'||busy)return;
    setBusy(true);setError('');
    try{await deleteAccount();await clearCatalogueCache().catch(()=>{});await resetAnalyticsIdentity().catch(()=>{});setConfirmation('');onDeleted();onClose();Alert.alert('PerkDrop data deleted','Saved items, private plans and connected-device access have been removed. Necessary transaction records may be retained without the account link. External bookings are not cancelled.');}
    catch(e){setError(e.message||'Deletion was not confirmed. Please try again or contact support.');}
    finally{setBusy(false);}
  };
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy)onClose();}}><SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.body} keyboardShouldPersistTaps="handled"><Pressable style={s.secondary} disabled={busy} onPress={onClose}><Text style={s.link}>Close</Text></Pressable><Text style={s.title}>Your PerkDrop</Text><Text style={s.text}>Browsing is free. Private saves and plans use a device-held identity. Keep private device links to yourself.</Text><Pressable style={s.secondary} onPress={()=>Linking.openURL('https://perkdrop.au/privacy').catch(()=>setError('Could not open privacy information.'))}><Text style={s.link}>Privacy policy</Text></Pressable><Pressable style={s.secondary} onPress={()=>Linking.openURL('https://perkdrop.au/contact').catch(()=>setError('Could not open support.'))}><Text style={s.link}>Help and support</Text></Pressable><Pressable style={s.secondary} onPress={()=>Linking.openSettings().catch(()=>setError('Open PerkDrop permissions in your phone settings.'))}><Text style={s.link}>Phone permissions</Text></Pressable><Pressable style={s.secondary} onPress={()=>clearCatalogueCache().then(()=>Alert.alert('Downloaded catalogue cleared','Your private saved items have not been deleted.')).catch(()=>setError('Could not clear downloaded data.'))}><Text style={s.link}>Clear downloaded catalogue</Text></Pressable><View style={[s.card,s.danger]}><Text style={s.title}>Delete PerkDrop data</Text><Text style={s.text}>This deletes the account’s saves, plans and connected-device access. You will lose access to passes. It does not cancel bookings with venues. Necessary transaction records may remain without your account link.</Text><Text style={s.text}>Type DELETE to confirm deletion across connected devices.</Text><TextInput value={confirmation} onChangeText={setConfirmation} editable={!busy} autoCapitalize="characters" autoCorrect={false} style={s.input} accessibilityLabel="Type DELETE to confirm account deletion"/><Pressable disabled={confirmation!=='DELETE'||busy} style={[s.button,(confirmation!=='DELETE'||busy)&&{opacity:0.4}]} onPress={remove}><Text style={s.label}>{busy?'Deleting…':'Delete my PerkDrop data'}</Text></Pressable></View>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}</ScrollView></SafeAreaView></Modal>;
}
