import React from 'react';
import Head from 'next/head';
const API='https://khzpdyyywiucfhubxkev.supabase.co/functions/v1/perkdrop-catalogue-api?limit=200';
const SITE='https://perkdrop.au';
const routeMeta={'/':['PerkDrop — Deals near you','Local food deals, drink specials, freebies, events and experiences worth knowing about.'],'/food':['Food deals | PerkDrop','Food and dining deals worth knowing about near you.'],'/drinks':['Drink specials | PerkDrop','Drink specials and venue offers worth knowing about.'],'/events':['Events | PerkDrop','Events worth knowing about near you.'],'/free':['Free stuff | PerkDrop','Free events, experiences and offers worth knowing about.'],'/kids':['Kids & family deals | PerkDrop','Family-friendly deals, events and freebies worth knowing about.'],'/shopping':['Shopping deals | PerkDrop','Shopping offers worth knowing about.'],'/map':['PerkDrop map','Explore nearby PerkDrop deals and venues on the map.'],'/business':['List your deal FREE | PerkDrop','Submit a genuine business offer or event for PerkDrop review.'],'/about':['About PerkDrop','PerkDrop helps Australians find worthwhile deals and helps businesses fill real capacity.']};
export default function Shell({deal,canonicalPath}){const h=React.createElement,meta=routeMeta[canonicalPath]||['PerkDrop — Deals near you','Deals worth knowing about.'];const title=deal?`${deal.merchant} — ${deal.title} | PerkDrop`:meta[0];const description=deal?(deal.description||`${deal.title} at ${deal.merchant}.`):meta[1];const canonical=deal?`${SITE}/deals/${encodeURIComponent(deal.slug)}`:`${SITE}${canonicalPath||'/'}`;return h(React.Fragment,null,h(Head,null,h('meta',{charSet:'utf-8'}),h('meta',{name:'viewport',content:'width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no'}),h('meta',{name:'theme-color',content:'#08090e'}),h('meta',{name:'description',content:description}),h('link',{rel:'canonical',href:canonical}),h('meta',{property:'og:type',content:'website'}),h('meta',{property:'og:site_name',content:'PerkDrop'}),h('meta',{property:'og:title',content:title}),h('meta',{property:'og:description',content:description}),h('meta',{property:'og:url',content:canonical}),deal?.image?h('meta',{property:'og:image',content:deal.image}):null,h('meta',{name:'twitter:card',content:deal?.image?'summary_large_image':'summary'}),h('meta',{name:'twitter:title',content:title}),h('meta',{name:'twitter:description',content:description}),deal?.image?h('meta',{name:'twitter:image',content:deal.image}):null,h('link',{rel:'manifest',href:'/manifest.webmanifest'}),h('link',{rel:'icon',href:'/icon.svg'}),h('title',null,title),h('link',{href:'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap',rel:'stylesheet'}),h('link',{rel:'stylesheet',href:'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css'}),h('link',{rel:'stylesheet',href:'/styles.css?v=v24-live-funnel'}),h('script',{src:'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js',defer:true})),h('div',{id:'app'},h('div',{className:'boot'},h('img',{src:'/icon.svg',className:'boot-icon',alt:''}),h('div',{className:'boot-logo'},'Perk',h('span',null,'Drop')),h('p',null,'Loading nearby Drops…'))),h('script',{src:'/app.js?v=v24-live-funnel',defer:true}));}
export async function getServerSideProps({params,resolvedUrl}){const canonicalPath=(resolvedUrl||'/').split('?')[0]||'/';const parts=params?.slug;if(!Array.isArray(parts)||parts[0]!=='deals'||!parts[1])return {props:{deal:null,canonicalPath}};try{const r=await fetch(API,{headers:{accept:'application/json'}});if(!r.ok)return{props:{deal:null,canonicalPath}};const p=await r.json(),deals=Array.isArray(p)?p:(p.deals||[]),requested=parts[1],m=deals.find(x=>x.slug===requested||x.detailUrl===`/deals/${requested}`);if(!m)return{notFound:true};return{props:{canonicalPath,deal:{slug:m.slug||requested,title:m.title||'Drop',merchant:m.merchant||'Local venue',description:m.description||m.conditions||'',image:m.image||m.imageUrl||m.mediaUrl||''}}}}catch{return{props:{deal:null,canonicalPath}}}}


