import {useEffect,useMemo,useState} from 'react';
import Head from 'next/head';
const BASE='https://khzpdyyywiucfhubxkev.supabase.co',KEY='sb_publishable_2UrOe1GGD02EMsYndb9rPw_TNctbZAl',API=BASE+'/functions/v1/';
const sections=['overview','live marketplace','merchants','demand','pilots','commercial','finance','partners','markets','quality','system health'];
const money=x=>'$'+Number(x||0).toFixed(2);
function Stat({label,value,detail}){return <article className="hq-stat"><small>{label}</small><strong>{value}</strong>{detail&&<span>{detail}</span>}</article>}
export default function Admin(){
 const [session,setSession]=useState(null),[data,setData]=useState(null),[analytics,setAnalytics]=useState(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[days,setDays]=useState(7);
 useEffect(()=>{let live=true;import('@supabase/supabase-js').then(({createClient})=>{const sb=createClient(BASE,KEY);sb.auth.getSession().then(({data})=>{if(live){setSession(data.session);if(data.session)load(data.session,days)}});sb.auth.onAuthStateChange((_e,s)=>{if(live){setSession(s);if(s)load(s,days)}})});return()=>{live=false}},[]);
 async function load(s=session,d=days){if(!s)return;setError('');try{const h={Authorization:'Bearer '+s.access_token,apikey:KEY};const [a,b]=await Promise.all([fetch(API+'perkdrop-admin-commercial',{headers:h,cache:'no-store'}),fetch(API+'perkdrop-owner-analytics?days='+d,{headers:h,cache:'no-store'})]);const aj=await a.json(),bj=await b.json();if(!a.ok)throw Error(aj.error||'HQ data unavailable');setData(aj);setAnalytics(bj)}catch(e){setError(e.message)}}
 const offers=data?.offers||[],reds=data?.redemptions||[],metrics=useMemo(()=>{const live=offers.filter(o=>o.status==='active'),customers=reds.filter(r=>r.status==='redeemed').reduce((n,r)=>n+Number(r.party_size||1),0),value=reds.filter(r=>r.status==='redeemed').reduce((n,r)=>n+Number(r.gross_value||0),0),fees=reds.filter(r=>r.status==='redeemed').reduce((n,r)=>n+Number(r.commission_value||0),0);return{live,customers,value,fees,redemptions:reds.filter(r=>r.status==='redeemed').length}},[offers,reds]);
 if(!session)return <><Head><title>PerkDrop HQ</title><meta name="robots" content="noindex,nofollow"/></Head><main className="hq-login"><h1>Perk<span>Drop</span> HQ</h1><p>Owner operations, marketplace supply and commercial control.</p><Login onLogin={s=>{setSession(s);load(s)}}/></main><Styles/></>;
 return <><Head><title>PerkDrop HQ</title><meta name="robots" content="noindex,nofollow"/></Head><main className="hq"><header><div><div className="eyebrow">PRIVATE OPERATIONS</div><h1>PerkDrop HQ</h1><p>Live operational evidence. Forecasts are never labelled as actuals.</p></div><div className="hq-actions"><button onClick={()=>load()}>Refresh</button><button onClick={async()=>{const {createClient}=await import('@supabase/supabase-js');await createClient(BASE,KEY).auth.signOut();setSession(null)}}>Sign out</button></div></header><nav className="hq-tabs" aria-label="HQ sections">{sections.map(s=><button key={s} className={tab===s?'on':''} onClick={()=>setTab(s)}>{s}</button>)}</nav>{error&&<p className="hq-error" role="alert">{error}</p>}
 {tab==='overview'&&<><div className="hq-grid"><Stat label="Customers delivered / active merchant / week" value={metrics.live.length?Math.round(metrics.customers/metrics.live.length):0} detail="Actual redeemed units"/><Stat label="Active Drops" value={metrics.live.length}/><Stat label="Available units" value={metrics.live.reduce((n,o)=>n+Number(o.capacity_remaining||0),0)}/><Stat label="Redemptions today" value={analytics?.overview?.redemptions??'Not tracked'}/><Stat label="Customers delivered" value={metrics.customers}/><Stat label="Tracked merchant value" value={money(metrics.value)}/><Stat label="PerkDrop accrued fees" value={money(metrics.fees)}/><Stat label="Active merchants" value={new Set(metrics.live.map(o=>o.merchant_id)).size}/></div><section className="hq-panel"><h2>North Star</h2><p className="hq-callout">CUSTOMERS DELIVERED PER ACTIVE MERCHANT PER WEEK</p><div className="hq-grid compact"><Stat label="Fill rate" value={analytics?.overview?.fillRate??'Not tracked'}/><Stat label="Active paying merchants" value="Not tracked" detail="No paying flag in current source"/><Stat label="Customer repeat rate" value="Not tracked"/><Stat label="Merchant retention" value="Not tracked"/></div></section></>}
 {tab==='live marketplace'&&<section className="hq-panel"><h2>Live marketplace operations</h2><p>Inspect live supply and open the authoritative Drop. Merchant mutations remain permissioned and audited by their API.</p><Table><thead><tr>{['Drop','Merchant','Vertical','Service','Capacity','Remaining','Status','View'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{metrics.live.map(o=><tr key={o.id}><td>{o.title}</td><td>{o.merchants?.name||'Merchant'}</td><td>{o.vertical||'—'}</td><td>{o.starts_at?new Date(o.starts_at).toLocaleString('en-AU'):'—'}</td><td>{o.capacity_total??'—'}</td><td>{o.capacity_remaining??'—'}</td><td>{o.status}</td><td><a href={'/deals/'+encodeURIComponent(o.published_drop_id||o.id)}>Open</a></td></tr>)}</tbody></Table></section>}
 {tab==='merchants'&&<section className="hq-panel"><h2>Merchant management</h2><Table><thead><tr><th>Business</th><th>Market</th><th>Status</th><th>Drops</th><th>Partner</th><th>Verified</th></tr></thead><tbody>{(data?.merchants||[]).map(m=><tr key={m.id}><td>{m.name}</td><td>{m.primary_city||'—'}</td><td>{m.listing_status||'—'}</td><td>{offers.filter(o=>o.merchant_id===m.id).length}</td><td>{m.partner_tier||'none'}</td><td>{m.verified_at?'yes':'review'}</td></tr>)}</tbody></Table></section>}
 {tab==='demand'&&<section className="hq-panel"><h2>Demand HQ</h2><p>Only active signals are shown. Individual customer identity is never exposed.</p><Table><thead><tr><th>City</th><th>Vertical</th><th>Type</th><th>Unit</th><th>Quantity</th><th>Expires</th></tr></thead><tbody>{(data?.demand||[]).map((d,i)=><tr key={i}><td>{d.city}</td><td>{d.vertical}</td><td>{d.drop_type}</td><td>{d.inventory_unit}</td><td>{d.quantity}</td><td>{new Date(d.expires_at).toLocaleString('en-AU')}</td></tr>)}</tbody></Table></section>}
 {tab==='pilots'&&<section className="hq-panel"><h2>Pilot pipeline</h2><p>Owner view of real merchant pilots. Stage changes remain audited server-side.</p><Table><thead><tr><th>Merchant</th><th>Stage</th><th>Goal</th><th>Owner</th><th>Window</th></tr></thead><tbody>{(data?.pilots||[]).map(p=><tr key={p.id}><td>{p.merchants?.name||p.merchant_id}</td><td><span className="hq-badge">{p.stage}</span></td><td>{p.goal||'—'}</td><td>{p.owner_email||'—'}</td><td>{shortDate(p.starts_at)} → {shortDate(p.ends_at)}</td></tr>)}</tbody></Table><ExportButton name="perkdrop-pilots.csv" rows={data?.pilots||[]}/></section>}
 {tab==='commercial'&&<section className="hq-panel"><h2>Commercial terms</h2><p>Contract records only. No forecast is presented as revenue.</p><Table><thead><tr><th>Merchant</th><th>Model</th><th>Rate</th><th>Flat</th><th>Monthly</th><th>Status</th><th>Effective</th></tr></thead><tbody>{(data?.commercial_terms||[]).map(t=><tr key={t.id}><td>{t.merchants?.name||t.merchant_id}</td><td>{t.model}</td><td>{t.commission_rate??'—'}</td><td>{t.commission_flat??'—'}</td><td>{t.monthly_fee??'—'}</td><td>{t.status}</td><td>{shortDate(t.effective_from)} → {shortDate(t.effective_to)}</td></tr>)}</tbody></Table><ExportButton name="perkdrop-commercial-terms.csv" rows={data?.commercial_terms||[]}/></section>}
 {tab==='finance'&&<section className="hq-panel"><h2>Finance & exports</h2><p>Ledger values below are the source of truth. Export produces the currently loaded, server-authorized rows.</p><div className="hq-grid compact"><Stat label="Ledger rows" value={(data?.ledger||[]).length}/><Stat label="Gross tracked" value={money((data?.ledger||[]).reduce((n,x)=>n+Number(x.gross_value||0),0))}/><Stat label="PerkDrop value" value={money((data?.ledger||[]).reduce((n,x)=>n+Number(x.perkdrop_value||0),0))}/><Stat label="Paid rows" value={(data?.ledger||[]).filter(x=>x.status==='paid').length}/></div><div className="hq-actions"><ExportButton name="perkdrop-ledger.csv" rows={data?.ledger||[]}/><ExportButton name="perkdrop-redemptions.csv" rows={data?.redemptions||[]}/><ExportButton name="perkdrop-merchants.csv" rows={data?.merchants||[]}/></div></section>}
 {tab==='partners'&&<section className="hq-panel"><h2>Partner operations</h2><p>Partner inventory, tier, and deep-link readiness from the merchant registry.</p><Table><thead><tr><th>Business</th><th>Tier</th><th>City</th><th>Since</th><th>Deep link</th></tr></thead><tbody>{(data?.merchants||[]).filter(m=>m.partner_tier&&m.partner_tier!=='none').map(m=><tr key={m.id}><td>{m.name}</td><td>{m.partner_tier}</td><td>{m.primary_city||'—'}</td><td>{shortDate(m.partner_since)}</td><td><a href={'/partner/'+(m.slug||m.id)}>Open landing page</a></td></tr>)}</tbody></Table><ExportButton name="perkdrop-partners.csv" rows={(data?.merchants||[]).filter(m=>m.partner_tier&&m.partner_tier!=='none')}/></section>}
 {tab==='markets'&&<section className="hq-panel"><h2>Market coverage</h2><p>Coverage is grouped from the live merchant and offer registry.</p><Table><thead><tr><th>Market</th><th>Merchants</th><th>Active drops</th><th>Available units</th></tr></thead><tbody>{marketRows(data?.merchants||[],offers).map(m=><tr key={m.city}><td>{m.city}</td><td>{m.merchants}</td><td>{m.active}</td><td>{m.units}</td></tr>)}</tbody></Table></section>}
 {tab==='quality'&&<section className="hq-panel"><h2>Quality control</h2><p>Reviewable quality signals from offers currently held in the marketplace.</p><Table><thead><tr><th>Drop</th><th>Merchant</th><th>Status</th><th>Image</th><th>Expiry</th><th>Capacity</th></tr></thead><tbody>{offers.slice(0,250).map(o=><tr key={o.id}><td>{o.title}</td><td>{o.merchants?.name||'—'}</td><td>{o.status}</td><td>{o.media_url?'ready':'needs image'}</td><td>{o.ends_at?shortDate(o.ends_at):'missing'}</td><td>{o.capacity_total??'missing'}</td></tr>)}</tbody></Table><ExportButton name="perkdrop-quality.csv" rows={offers}/></section>}
 {tab==='system health'&&<section className="hq-panel"><h2>System health</h2><div className="hq-grid compact"><Stat label="Live offers" value={metrics.live.length}/><Stat label="Notifications pending" value={(data?.notifications||[]).filter(x=>x.status==='pending_provider').length}/><Stat label="Open demand" value={(data?.demand||[]).length}/><Stat label="Groups" value={(data?.groups||[]).length}/></div><p>Catalogue, marketplace API, merchant API, redeem, booking, and owner API are deployed. Notification and report outboxes truthfully remain pending_provider until their provider is configured.</p><Table><thead><tr><th>Outbox event</th><th>Recipient</th><th>Status</th><th>Created</th><th>Error</th></tr></thead><tbody>{(data?.notifications||[]).slice(0,100).map(n=><tr key={n.id}><td>{n.event_type}</td><td>{n.recipient_email}</td><td>{n.status}</td><td>{shortDate(n.created_at)}</td><td>{n.last_error||'—'}</td></tr>)}</tbody></Table></section>}
 <footer><a href="/claim">Merchant portal</a> · <a href="/merchant-floor">Floor redemption</a> · <a href="/">Public marketplace</a></footer></main><Styles/></>;
}
export function getServerSideProps({res}){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Robots-Tag','noindex, nofollow');res.setHeader('Referrer-Policy','no-referrer');return{props:{}}}
function Login({onLogin}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');return <form className="hq-login-form" onSubmit={async e=>{e.preventDefault();const {createClient}=await import('@supabase/supabase-js');const {data,error}=await createClient(BASE,KEY).auth.signInWithPassword({email,password});if(error)setError('Could not sign in.');else onLogin(data.session)}}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Open HQ</button>{error&&<p role="alert">{error}</p>}</form>}
function shortDate(v){return v?new Date(v).toLocaleDateString('en-AU'):'—'}
function marketRows(merchants,offers){const map={};for(const m of merchants){const city=m.primary_city||'unassigned';map[city]??={city,merchants:0,active:0,units:0};map[city].merchants++}for(const o of offers.filter(x=>x.status==='active')){const city=o.city||o.merchants?.primary_city||'unassigned';map[city]??={city,merchants:0,active:0,units:0};map[city].active++;map[city].units+=Number(o.capacity_remaining||0)}return Object.values(map).sort((a,b)=>a.city.localeCompare(b.city))}
function ExportButton({name,rows}){return <button className="hq-button" onClick={()=>{const keys=[...new Set(rows.flatMap(x=>Object.keys(x||{})))];const csv=[keys.join(','),...rows.map(x=>keys.map(k=>`"${String(x?.[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}}>Export CSV</button>}
function Table({children}){return <div className="hq-table-wrap"><table>{children}</table></div>}
function Styles(){return <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#08090e;color:#f8f7ff;font:14px/1.5 Arial,sans-serif}a{color:#ff8bca}.hq,.hq-login{max-width:1220px;margin:auto;padding:24px 18px 80px}.hq header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.hq h1,.hq-login h1{font-size:clamp(32px,6vw,58px);margin:4px 0}.hq h1 span,.hq-login h1 span{color:#ff55b9}.hq p{color:#b8b7c8}.eyebrow{color:#ff72c1;font-weight:800;letter-spacing:1px;font-size:11px}.hq-actions,.hq-tabs{display:flex;gap:9px;flex-wrap:wrap}.hq-actions button,.hq-tabs button,.hq-button,.hq-login button,.hq-panel button{border:1px solid #41455c;background:#171a27;color:#fff;border-radius:10px;padding:10px 13px;cursor:pointer;text-decoration:none}.hq-tabs{margin:24px 0 14px;border-bottom:1px solid #2d3142;padding-bottom:10px}.hq-tabs .on{background:#ff4db8;color:#170b14;border-color:#ff4db8}.hq-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.hq-grid.compact{grid-template-columns:repeat(4,minmax(0,1fr))}.hq-stat,.hq-panel{background:#131620;border:1px solid #303548;border-radius:16px;padding:16px}.hq-stat small,.hq-stat span{display:block;color:#aeb2c2}.hq-stat strong{display:block;font-size:27px;margin:8px 0}.hq-panel{margin-top:16px}.hq-callout{color:#ff8bca;font-size:22px;font-weight:800}.hq-table-wrap{overflow:auto}.hq table{width:100%;border-collapse:collapse;min-width:760px}.hq th,.hq td{text-align:left;padding:10px;border-bottom:1px solid #2b3041}.hq-error{color:#ff9baa}.hq-login{max-width:520px}.hq-login-form{display:grid;gap:14px;background:#131620;border:1px solid #303548;border-radius:16px;padding:20px}.hq-login-form label{display:grid;gap:6px}.hq-login-form input{padding:12px;border-radius:8px;border:1px solid #555b72;background:#0d1019;color:#fff}.hq-login-form button{background:#ff4db8;color:#170b14;border:0;font-weight:800}@media(max-width:800px){.hq-grid,.hq-grid.compact{grid-template-columns:repeat(2,minmax(0,1fr))}.hq header{display:block}}@media(max-width:450px){.hq,.hq-login{padding:16px 12px 60px}.hq-grid,.hq-grid.compact{grid-template-columns:1fr}.hq-tabs{overflow:auto;flex-wrap:nowrap}.hq-tabs button{white-space:nowrap}}`}</style>}
