import {useEffect,useState} from 'react';
import PrivateShell,{privateResponse} from '../components/PrivateShell';
import {marketplace,marketplacePublic,newCredential,IDENTITY_KEY} from '../lib/marketplace-client';
export default function ConnectDevice(){
 const [token,setToken]=useState(''),[link,setLink]=useState(null),[devices,setDevices]=useState([]),[label,setLabel]=useState('My browser'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const d=await marketplace('devices');setDevices(d.devices);}
 useEffect(()=>{const t=location.hash.slice(1);if(/^[a-f0-9]{64}$/.test(t)){setToken(t);history.replaceState(null,'','/connect-device'+location.search);}else load().catch(e=>setError(e.message));},[]);
 async function connect(e){e.preventDefault();setBusy(true);setError('');try{const next=newCredential();await marketplacePublic('device_connect',{token,new_credential:next,label});localStorage.setItem(IDENTITY_KEY,next);for(const k of ['perkdrop_saved','perkdrop_followed_merchants','perkdrop_preferences_v1'])localStorage.removeItem(k);const nextPath=new URLSearchParams(location.search).get('next');location.replace(nextPath&&/^\/plans(?:\?|$)/.test(nextPath)?nextPath:'/my-perks?tab=saved');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function create(){setBusy(true);setError('');try{setLink(await marketplace('device_link'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function revoke(id){setBusy(true);try{await marketplace('device_revoke',{id});await load();setMessage('Device disconnected.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <PrivateShell title="Connect your devices">{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}{token?<section><h2>Use the same saved Drops and plans here</h2><p>Continue only if you created this link on your own device. This replaces this browser’s current PerkDrop access; separate saved items are not merged. Your original device stays connected.</p><form onSubmit={connect}><label>Name this device<input required maxLength="80" value={label} onChange={e=>setLabel(e.target.value)}/></label><button disabled={busy}>Connect this browser</button></form></section>:<><section><h2>Connect another phone or browser</h2><p>Create a private link, then open it on your other device. It works once and expires after 10 minutes. Treat it like a password.</p><button disabled={busy} onClick={create}>Create private device link</button>{link&&<div className="share-link"><p>Expires {new Date(link.expires_at).toLocaleTimeString()}.</p><input aria-label="Private device link" readOnly value={link.url}/><div className="actions"><button onClick={()=>navigator.clipboard.writeText(link.url).then(()=>setMessage('Private link copied.')).catch(()=>setError('Copy the link from the field.'))}>Copy for another browser</button><a className="action" href={link.app_url}>Connect the PerkDrop app</a></div></div>}</section><section><h2>Connected devices</h2>{devices.filter(d=>!d.revoked_at).map(d=><p key={d.id}>{d.label}{d.current?' (this device)':''} {!d.current&&<button disabled={busy} onClick={()=>revoke(d.id)}>Disconnect</button>}</p>)}<p className="muted">The original browser or app keeps its original access. Email recovery requires a configured email service and is not enabled. Keep at least one connected device available.</p></section></>}</PrivateShell>;
}
export const getServerSideProps=privateResponse;
