import Head from 'next/head';
import {useEffect,useState} from 'react';
const BASE=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://khzpdyyywiucfhubxkev.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
export default function MerchantTeam(){
 const [session,setSession]=useState(null),[data,setData]=useState(null),[merchant,setMerchant]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('manager'),[message,setMessage]=useState('');
 async function load(s=session){if(!s)return;const r=await fetch(BASE+'/functions/v1/perkdrop-merchant-api',{headers:{Authorization:'Bearer '+s.access_token,apikey:KEY}});const j=await r.json();if(!r.ok)throw Error(j.error||'Could not load team');setData(j);if(!merchant&&j.merchants?.[0])setMerchant(j.merchants[0].id)}
 useEffect(()=>{(async()=>{const {createClient}=await import('@supabase/supabase-js');const {data}=await createClient(BASE,KEY).auth.getSession();setSession(data.session);if(data.session)await load(data.session)})().catch(e=>setMessage(e.message))},[]);
 const current=data?.merchants?.find(x=>x.id===merchant),canAdmin=['owner','admin'].includes(current?.role);
 async function act(body){const r=await fetch(BASE+'/functions/v1/perkdrop-merchant-api',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({...body,merchant_id:merchant})});const j=await r.json();if(!r.ok)throw Error(j.error||'Action failed');if(j.invite_url)await navigator.clipboard?.writeText(j.invite_url);setMessage(j.invite_url?'Invite link copied.':'Saved.');await load()}
 if(!session)return <main><Head><title>PerkDrop Team</title></Head><h1>Merchant team</h1><p>{message||'Sign in through the merchant portal first.'}</p><a href="/claim">Open merchant portal</a></main>;
 return <main><Head><title>PerkDrop Team</title><meta name="robots" content="noindex,nofollow"/></Head><header><h1>Merchant team</h1><a href="/claim">Back to portal</a></header>{message&&<p role="status">{message}</p>}<label>Business <select value={merchant} onChange={e=>setMerchant(e.target.value)}>{(data?.merchants||[]).map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select></label>{current&&<div><section><h2>Active team members</h2>{(current.members||[]).filter(m=>m.status==='active').map(m=><div key={m.user_id}><span>{m.user?.name||m.user?.email||'Team member'} · {m.user?.email||'Email hidden'} · joined {new Date(m.created_at).toLocaleDateString('en-AU')}</span>{canAdmin&&m.role!=='owner'?<><select value={m.role} onChange={e=>act({action:'member_role',user_id:m.user_id,role:e.target.value})}><option>admin</option><option>manager</option><option>floor</option><option>viewer</option></select><button onClick={()=>act({action:'member_remove',user_id:m.user_id})}>Remove</button></>:<b>{m.role}</b>}</div>)}</section><section><h2>Invitations</h2>{(current.invites||[]).map(i=><div key={i.id}><span>{i.email} · {i.role} · {i.revoked_at?'REVOKED':i.accepted_at?'ACCEPTED':new Date(i.expires_at)<new Date()?'EXPIRED':'PENDING'}</span>{canAdmin&&!i.accepted_at&&!i.revoked_at&&<><button onClick={()=>act({action:'invite_revoke',invite_id:i.id})}>Revoke</button><button onClick={()=>act({action:'invite_reissue',invite_id:i.id})}>Reissue + copy</button></>}</div>)}</section>{canAdmin&&<form onSubmit={e=>{e.preventDefault();act({action:'invite_create',email,role}).then(()=>setEmail(''))}}><h2>Invite member</h2><input aria-label="Invite email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><select aria-label="Invite role" value={role} onChange={e=>setRole(e.target.value)}><option>admin</option><option>manager</option><option>floor</option><option>viewer</option></select><button>Invite and copy link</button></form>}</div>}</main>;
}
export function getServerSideProps({res}){res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Robots-Tag','noindex, nofollow');return{props:{}}}
