import {useEffect,useState} from 'react';
import PrivateShell,{privateResponse} from '../components/PrivateShell';
import {marketplace,passState,units} from '../lib/marketplace-client';
export default function MyPerks(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('upcoming'),[recovery,setRecovery]=useState(null),[busy,setBusy]=useState(false);
  async function refresh(){setError('');try{setData(await marketplace('my_perks'));}catch(e){setError(e.message);}}
  useEffect(()=>{if(new URLSearchParams(location.search).get('tab')==='saved')setTab('saved');refresh();},[]);
  async function recoveryLink(){setBusy(true);try{setRecovery(await marketplace('recovery_link'));}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function removeSave(s){try{await marketplace('save',{kind:s.kind,target:s.target,remove:true});if(s.kind==='drop'){try{const cached=JSON.parse(localStorage.getItem('perkdrop_saved')||'[]');localStorage.setItem('perkdrop_saved',JSON.stringify(cached.filter(id=>id!==s.target)));}catch{}}await refresh();}catch(e){setError(e.message);}}
  const passes=(data?.redemptions||[]).filter(p=>tab==='upcoming'?['active','pending'].includes(passState(p)):!['active','pending'].includes(passState(p)));
  return <PrivateShell title="Saved & passes"><p className="muted">Keep worthwhile deals here. Any booked or claimed passes appear below.</p>
    {data&&<section><h2>Your local guide</h2><p>Personalise Home picks, turn saved Drops into a plan, or check your Radar updates.</p><div className="actions"><a className="action" href="/preferences">Tune Home picks</a><a className="action" href="/plans">Make a plan</a><a className="action" href="/updates">Updates{data.updates_unread?` (${data.updates_unread} new)`:''}</a></div></section>}
    {error&&<p role="alert" className="error">{error} <button onClick={refresh}>Retry</button></p>}
    <div className="tabs" aria-label="My Perks sections">{['upcoming','past','saved','watching'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t.toUpperCase()}</button>)}</div>
    {!data&&!error&&<p role="status">Loading your Perks…</p>}
    {data&&['upcoming','past'].includes(tab)&&<>{passes.map(p=><section key={p.id}><span className="status">{passState(p)==='pending'?'Pending merchant confirmation':passState(p)}</span><h2>{p.metadata?.offer_title||'Your PerkDrop'}</h2><p>{units(p.metadata?.inventory_unit,p.party_size)}</p><p className="muted">{p.metadata?.valid_from?new Date(p.metadata.valid_from).toLocaleString('en-AU'):'See pass for service instructions'}</p><a className="action" href={'/perk#'+p.pass_reference}>View pass & QR</a></section>)}{!passes.length&&<section>No {tab} passes. <a href="/now">Explore available Drops.</a></section>}</>}
    {data&&tab==='saved'&&<section><h2>Saved Drops & businesses</h2>{data.saves.length?data.saves.map(s=><p key={s.kind+s.target}>{s.href?<a href={s.href}>{s.label}</a>:<span>{s.label||'Saved listing unavailable'}</span>} <button onClick={()=>removeSave(s)}>Remove</button></p>):<p>No saved Drops or followed businesses yet.</p>}<div className="actions"><a className="action" href="/plans">Build a plan from saved Drops</a></div></section>}
    {data&&tab==='watching'&&<section><h2>Deal alerts</h2><p>Choose the categories, places and times you want to hear about.</p><a href="/radar" className="action">Manage alerts</a></section>}
    <section><h2>Keep your devices connected</h2><p>Connect your phone and browser to the same saved Drops, plans and passes. Each device keeps its own private access.</p><a className="action" href="/connect-device">Connect or manage devices</a></section><details><summary>Transfer access / recover access</summary><section><h2>Move your saved deals and passes</h2><p>This browser keeps your private access. A transfer link works once, expires in 15 minutes and signs this browser out. Keep it private, like a password.</p><button disabled={busy} onClick={recoveryLink}>Create private transfer link</button>{recovery&&<div role="status"><p>Expires {new Date(recovery.expires_at).toLocaleTimeString()}. Copy the link to your other device.</p><button onClick={()=>navigator.clipboard.writeText(recovery.url).catch(()=>setError('Could not copy. Use the link below.'))}>Copy private link</button><p><a href={recovery.url} rel="noreferrer">Open transfer link</a></p></div>}<p className="muted">Email recovery is not enabled yet, so create a transfer link before moving or replacing this device.</p></section></details>
  </PrivateShell>;
}
export const getServerSideProps=privateResponse;
