import {useEffect,useState} from 'react';
import PrivateShell,{privateResponse} from '../components/PrivateShell';
import {marketplace} from '../lib/marketplace-client';

const emptyDraft={name:'',planned_for:'',note:'',item_ids:[]};
export default function Plans(){
  const [plans,setPlans]=useState(null),[saves,setSaves]=useState([]),[draft,setDraft]=useState(emptyDraft),[share,setShare]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  async function load(){setError('');try{const [planData,perkData]=await Promise.all([marketplace('plans'),marketplace('my_perks')]);setPlans(planData.plans);setSaves((perkData.saves||[]).filter(item=>item.kind==='drop'&&item.href));}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[]);
  function toggle(id){setDraft(current=>({...current,item_ids:current.item_ids.includes(id)?current.item_ids.filter(item=>item!==id):[...current.item_ids,id].slice(0,12)}));}
  async function save(event){event.preventDefault();setBusy(true);setError('');try{await marketplace('plan_save',draft);setDraft(emptyDraft);setMessage('Plan saved. You can create a private share link when you are ready.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function sharePlan(id){setBusy(true);setError('');try{const result=await marketplace('plan_share',{id});setShare(current=>({...current,[id]:result.share_url}));setMessage('Private share link created. Anyone with it can see this plan until you revoke or replace it.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function revoke(id){setBusy(true);setError('');try{await marketplace('plan_share',{id,revoke:true});setShare(current=>{const next={...current};delete next[id];return next;});setMessage('That share link has been revoked.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function remove(id){if(!window.confirm('Delete this plan?'))return;setBusy(true);setError('');try{await marketplace('plan_delete',{id});setMessage('Plan deleted.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function copyShare(url){try{if(!navigator.clipboard?.writeText)throw new Error('copy_unavailable');await navigator.clipboard.writeText(url);setMessage('Private share link copied.');}catch{setError('Could not copy the link.');}}
  return <PrivateShell title="Make a plan"><p className="muted">Build a simple shortlist from saved Drops, then share it privately. Plans are reminders, not bookings or reservations.</p>
    {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}
    <section><h2>New plan</h2><form onSubmit={save}><label>Plan name<input value={draft.name} maxLength="100" required placeholder="Friday night in the city" onChange={e=>setDraft(current=>({...current,name:e.target.value}))}/></label><label>When (optional)<input type="date" value={draft.planned_for} onChange={e=>setDraft(current=>({...current,planned_for:e.target.value}))}/></label><label>Note (optional)<textarea value={draft.note} maxLength="600" rows="3" placeholder="Meeting at 6. Check each venue’s current availability." onChange={e=>setDraft(current=>({...current,note:e.target.value}))}/></label><fieldset><legend>Add saved Drops (up to 12)</legend>{saves.length?<div className="choice-grid">{saves.map(item=><label key={item.target}><input type="checkbox" checked={draft.item_ids.includes(item.target)} onChange={()=>toggle(item.target)}/> {item.label}</label>)}</div>:<p>Save a few Drops first, then come back to build a plan.</p>}</fieldset><button disabled={busy||!draft.item_ids.length}>{busy?'Saving…':'Save plan'}</button></form></section>
    {!plans&&!error&&<p role="status">Loading plans…</p>}
    {plans?.map(plan=><section key={plan.id}><div className="section-row"><div><h2>{plan.name}</h2><p className="muted">{plan.planned_for?new Date(`${plan.planned_for}T12:00:00`).toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long'}):'No date set'}</p></div><span className="status">{plan.share_created_at&&!plan.share_revoked_at?'Shared':'Private'}</span></div>{plan.note&&<p>{plan.note}</p>}<ol>{plan.items.map(item=><li key={item.id}>{item.href?<a href={item.href}>{item.merchant} — {item.title}</a>:<span>{item.merchant?`${item.merchant} — `:''}{item.title}</span>}{!item.available&&' (no longer available)'}</li>)}</ol><div className="actions"><button disabled={busy} onClick={()=>sharePlan(plan.id)}>Create / replace share link</button>{plan.share_created_at&&!plan.share_revoked_at&&<button disabled={busy} onClick={()=>revoke(plan.id)}>Revoke share link</button>}<button disabled={busy} onClick={()=>remove(plan.id)}>Delete</button></div>{share[plan.id]&&<div className="share-link"><p>Share this private link:</p><input aria-label="Private plan link" readOnly value={share[plan.id]}/><button onClick={()=>copyShare(share[plan.id])}>Copy link</button></div>}</section>)}
    {plans&&plans.length===0&&<section><h2>Your first plan starts with saved Drops</h2><p>Browse the local guide, save the places you like, then use this space to group them into a night out, weekend or family plan.</p><a className="action" href="/">Find Drops</a></section>}
  </PrivateShell>;
}
export const getServerSideProps=privateResponse;
