import {useEffect,useState} from 'react';
import PrivateShell,{privateResponse} from '../components/PrivateShell';
import {marketplace} from '../lib/marketplace-client';
const categories=['food','events','beauty','wellness','experiences','activities','fitness','stay','shopping','free'];
export default function Radar(){
  const [watches,setWatches]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[geo,setGeo]=useState(null);
  const reload=()=>marketplace('watches').then(x=>setWatches(x.watches)).catch(e=>setError(e.message));
  useEffect(()=>{reload();},[]);
  async function save(e){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{
    const rule={city:data.get('city'),precinct:data.get('precinct'),verticals:data.getAll('verticals'),drop_types:data.getAll('drop_types'),times:data.getAll('times'),daily_cap:Number(data.get('daily_cap')),quiet_start:Number(data.get('quiet_start')),quiet_end:Number(data.get('quiet_end')),timezone:data.get('timezone')};
    if(data.get('radius_km')){if(!geo)throw new Error('Use your location before choosing a radius.');Object.assign(rule,geo,{radius_km:Number(data.get('radius_km'))});}
    await marketplace('watch_save',{name:data.get('name'),rule});await reload();setMessage('Watch saved. Matching alerts will queue; email transport is not connected and no SMS is sent.');
  }catch(e){setError(e.message);}finally{setBusy(false);}}
  return <PrivateShell title="Drop Radar"><p>Watch the kinds of Drops you want, where and when they suit you.</p>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    {watches.map(w=><section key={w.id}><h2>{w.name}</h2><p>{w.rule.city} · {w.rule.verticals?.join(', ')||'All categories'} · {w.active?'Watching':'Paused'}</p><div className="actions"><button onClick={async()=>{try{await marketplace('watch_save',{...w,active:!w.active});await reload();}catch(e){setError(e.message);}}}>{w.active?'Pause':'Resume'}</button><button onClick={async()=>{try{await marketplace('watch_delete',{id:w.id});await reload();}catch(e){setError(e.message);}}}>Delete</button></div></section>)}
    <section><h2>Create a watch</h2><form onSubmit={save}><label>Watch name<input name="name" required maxLength="120" placeholder="Beauty cancellations near home"/></label><label>City<input name="city" required defaultValue="adelaide"/></label><label>Precinct / suburb (optional)<input name="precinct" placeholder="norwood"/></label><fieldset><legend>Categories</legend>{categories.map(c=><label key={c}><span><input type="checkbox" name="verticals" value={c} style={{width:'auto'}}/> {c}</span></label>)}</fieldset><fieldset><legend>Drop types (empty means all)</legend>{['cancellation','last_minute','exclusive'].map(c=><label key={c}><span><input type="checkbox" name="drop_types" value={c} style={{width:'auto'}}/> {c.replaceAll('_',' ')}</span></label>)}</fieldset><fieldset><legend>Service times</legend>{['morning','lunch','afternoon','evening','weekend'].map(c=><label key={c}><span><input type="checkbox" name="times" value={c} style={{width:'auto'}}/> {c}</span></label>)}</fieldset>
      <button type="button" onClick={()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{setGeo({latitude:p.coords.latitude,longitude:p.coords.longitude});setMessage('Location set for this watch.');},()=>setError('Location unavailable. You can still watch a city or precinct.')):setError('Location is not supported.')}>Use location for radius</button><label>Radius (km, optional)<input name="radius_km" type="number" min="1" max="100"/></label><label>Timezone<select name="timezone"><option>Australia/Adelaide</option><option>Australia/Sydney</option><option>Australia/Brisbane</option><option>Australia/Perth</option><option>Australia/Darwin</option></select></label><label>Daily alert cap<input name="daily_cap" type="number" min="1" max="10" defaultValue="3" required/></label><label>Quiet hours start (0–23)<input name="quiet_start" type="number" min="0" max="23" defaultValue="22"/></label><label>Quiet hours end (0–23)<input name="quiet_end" type="number" min="0" max="23" defaultValue="7"/></label><button disabled={busy}>Save watch</button></form></section>
    <a href="/standby">Free today? Tell nearby businesses what you’re looking for.</a></PrivateShell>;
}
export const getServerSideProps=privateResponse;
