import {useState} from 'react';
import PrivateShell,{privateResponse} from '../components/PrivateShell';
import {marketplace} from '../lib/marketplace-client';
export default function Standby(){
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{await marketplace('standby',{city:data.get('city'),precinct:data.get('precinct'),vertical:data.get('vertical'),time_window:data.get('time_window'),quantity:Number(data.get('quantity')),radius_km:Number(data.get('radius_km')),budget:data.get('budget'),expires_at:new Date(data.get('expires_at')).toISOString()});setMessage('You’re on standby. Businesses only see coarse demand groups of at least ten distinct people—not your identity or exact location. This is not a booking.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <PrivateShell title="I’m free"><p>Let businesses know what you’d like to do. No bidding, no obligation, and no promise of a match.</p><section><form onSubmit={submit}><label>What are you looking for?<select name="vertical"><option value="food">Lunch / dinner</option><option value="beauty">Beauty appointment</option><option value="experiences">Something to do</option><option value="activities">Family activity / golf</option><option value="other">Other</option></select></label><label>City<input name="city" defaultValue="adelaide" required/></label><label>Precinct / suburb<input name="precinct" required placeholder="norwood"/></label><label>Time window<select name="time_window"><option>Lunch today</option><option>Dinner tonight</option><option>Tomorrow morning</option><option>Tomorrow afternoon</option><option>This weekend</option></select></label><label>Radius (km)<input name="radius_km" type="number" min="1" max="100" defaultValue="5" required/></label><label>People / places needed<input name="quantity" type="number" min="1" max="20" defaultValue="1" required/></label><label>Budget (optional, $)<input name="budget" type="number" min="0" max="10000" step="1"/></label><label>Stop showing my interest after<input name="expires_at" type="datetime-local" required/></label><button disabled={busy}>I’m available</button></form>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}</section></PrivateShell>;
}
export const getServerSideProps=privateResponse;
