import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const SUPABASE='https://khzpdyyywiucfhubxkev.supabase.co';
const REDEEM=`${SUPABASE}/functions/v1/perkdrop-redeem`;
const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string));
const fmt=(v:unknown)=>{if(!v)return '';const d=new Date(String(v));if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Adelaide',weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(d)};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});

Deno.serve(async(req)=>{
  if(req.method!=='GET')return json({ok:false,error:'method_not_allowed'},405);
  try{
    const url=new URL(req.url),dropId=clean(url.searchParams.get('drop'),80);
    if(!/^PD-\d{4}-\d{4}$/.test(dropId))return new Response('Invalid Drop',{status:400});
    const service=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const {data:drop}=await service.from('catalogue_items').select('id,merchant_id,merchant,title,description,location,timing,price,conditions,slug,detail_url,image_url,exclusive,active,metadata').eq('id',dropId).eq('active',true).maybeSingle();
    if(!drop)return Response.redirect('https://perkdrop.au/deals',302);
    const offerId=clean(drop.metadata?.merchant_offer_id,80);
    if(!offerId)return Response.redirect(`https://perkdrop.au${drop.detail_url||'/deals'}`,302);
    const {data:offer}=await service.from('merchant_offers').select('id,merchant_id,title,description,discount_percent,normal_price,deal_price,conditions,starts_at,ends_at,capacity_total,capacity_remaining,booking_url,exclusive,status').eq('id',offerId).eq('merchant_id',drop.merchant_id).eq('status','active').maybeSingle();
    if(!offer)return Response.redirect(`https://perkdrop.au${drop.detail_url||'/deals'}`,302);
    const remaining=offer.capacity_remaining===null?null:Math.max(0,Number(offer.capacity_remaining)||0),total=offer.capacity_total===null?null:Math.max(0,Number(offer.capacity_total)||0),sold=remaining!==null&&remaining<=0;
    const windowText=offer.starts_at&&offer.ends_at?`${fmt(offer.starts_at)} – ${fmt(offer.ends_at)}`:offer.ends_at?`Ends ${fmt(offer.ends_at)}`:drop.timing||'Available during the stated offer period';
    const detail=`https://perkdrop.au${drop.detail_url||`/deals/${drop.slug}`}`;
    const booking=clean(offer.booking_url,1600);
    const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08090e"><title>${esc(drop.title)} | PerkDrop</title><style>
*{box-sizing:border-box}body{margin:0;background:#08090e;color:#f5f6f8;font-family:Poppins,Arial,sans-serif;min-height:100vh}.wrap{max-width:620px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-size:25px;font-weight:900;text-decoration:none;color:#fff}.brand span{background:linear-gradient(135deg,#ff4db8,#6c3bff);-webkit-background-clip:text;color:transparent}.back{color:#b7bdc8;text-decoration:none;font-weight:700}.hero{overflow:hidden;border:1px solid #2c3140;border-radius:24px;background:#11131b}.photo{height:230px;background:#191c26 center/cover no-repeat}.body{padding:20px}.eyebrow{color:#ff65c2;font-size:12px;font-weight:900;letter-spacing:1.2px}.title{font-size:32px;line-height:1.05;margin:8px 0 5px}.merchant{color:#c4cad4;font-weight:700}.pill{display:inline-block;margin-top:14px;padding:7px 10px;border:1px solid #4a3e6e;background:#221a38;border-radius:999px;font-size:12px;font-weight:900}.remaining{font-size:28px;font-weight:900;margin:18px 0 4px;color:${sold?'#ff7c91':'#30e0c1'}}.total{color:#9ca4b2;font-size:12px}.facts{margin:18px 0;padding:14px;border:1px solid #303546;border-radius:15px;background:#0d0f17;line-height:1.7}.catch{margin:14px 0;padding:14px;border-left:3px solid #ffc700;background:#17160d;border-radius:8px}.claim{width:100%;border:0;border-radius:15px;padding:15px 16px;background:linear-gradient(135deg,#ff4db8,#6c3bff);color:white;font-size:16px;font-weight:900;cursor:pointer}.claim:disabled{background:#343845;color:#9299a5;cursor:not-allowed}.note{color:#9da5b3;font-size:12px;line-height:1.5;margin-top:12px}.error{display:none;margin-top:12px;padding:10px;border-radius:10px;background:#30131a;color:#ff9baa}.success{display:none;margin-top:18px;padding:18px;border:1px solid #277866;border-radius:18px;background:#0e241f}.success h2{margin:0 0 7px;color:#30e0c1}.code{font-size:36px;font-weight:900;letter-spacing:2px;margin:12px 0;padding:14px;text-align:center;border:1px dashed #677080;border-radius:14px;background:#08090e}.copy,.book{display:block;width:100%;text-align:center;border:1px solid #41485a;border-radius:12px;padding:12px;margin-top:9px;background:#171a24;color:#fff;font-weight:800;text-decoration:none}.book{border:0;background:linear-gradient(135deg,#ff4db8,#6c3bff)}.footer{text-align:center;color:#737b8c;font-size:11px;padding:24px 0}.sold{color:#ff8a9c}.live{color:#30e0c1;font-weight:800}@media(max-width:520px){.wrap{padding:12px}.photo{height:205px}.title{font-size:28px}.body{padding:17px}.code{font-size:30px}}
</style></head><body><div class="wrap"><div class="top"><a class="brand" href="https://perkdrop.au">Perk<span>Drop</span></a><a class="back" href="${esc(detail)}">← Back to Drop</a></div><section class="hero"><div class="photo" style="background-image:url('${esc(drop.image_url||'')}')"></div><div class="body"><div class="eyebrow">${offer.exclusive||drop.exclusive?'🔥 PERKDROP EXCLUSIVE':'PERKDROP DROP'}</div><h1 class="title">${esc(drop.title)}</h1><div class="merchant">${esc(drop.merchant)}</div><div class="pill">${esc(drop.price||'PerkDrop offer')}</div><div id="remaining" class="remaining ${sold?'sold':''}">${sold?'SOLD OUT':remaining===null?'LIMITED AVAILABILITY':remaining===1?'1 DEAL LEFT':`${remaining} DEALS LEFT`}</div>${total!==null?`<div id="total" class="total">${remaining||0} of ${total} PerkDrop allocations remaining</div>`:''}<div class="facts"><b>📍 ${esc(drop.location||'Check venue')}</b><br>◷ ${esc(windowText)}</div><p>${esc(drop.description||'')}</p><div class="catch"><b>THE CATCH</b><br>${esc(drop.conditions||offer.conditions||'Show your PerkDrop code to the venue and follow the stated offer conditions.')}</div><button id="claim" class="claim" ${sold?'disabled':''}>${sold?'Sold out':'Claim this Drop'}</button><div class="note">Claiming reserves one of this venue's limited PerkDrop allocations. You’ll receive a unique code to show the venue. If a separate table booking is required, complete it after claiming.</div><div id="error" class="error"></div><div id="success" class="success"><h2>DROP CLAIMED</h2><div>Show this code at ${esc(drop.merchant)}:</div><div id="code" class="code"></div><button id="copy" class="copy">Copy code</button>${booking?`<a class="book" href="${esc(booking)}" target="_blank" rel="noopener">Continue to venue booking →</a>`:''}<div class="note">Keep this code until the offer is redeemed.</div></div></div></section><div class="footer">PerkDrop · Limited offers can sell out · Merchant conditions apply.</div></div><script>
const DROP=${JSON.stringify(drop.id)},OFFER=${JSON.stringify(offer.id)},REDEEM=${JSON.stringify(REDEEM)};let remaining=${remaining===null?'null':remaining};const key='perkdrop_redemption_session';let sid='';try{sid=localStorage.getItem(key)||'';if(!sid){sid=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(key,sid)}}catch{sid=Date.now()+'-'+Math.random().toString(36).slice(2)}
const btn=document.getElementById('claim'),err=document.getElementById('error'),ok=document.getElementById('success'),code=document.getElementById('code');function showError(t){err.textContent=t;err.style.display='block'}function updateLeft(n){if(n===null||n===undefined)return;remaining=Number(n);const e=document.getElementById('remaining'),t=document.getElementById('total');e.textContent=remaining<=0?'SOLD OUT':remaining===1?'1 DEAL LEFT':remaining+' DEALS LEFT';if(t)t.textContent=remaining+' of ${total??0} PerkDrop allocations remaining'}
btn?.addEventListener('click',async()=>{btn.disabled=true;btn.textContent='Claiming…';err.style.display='none';try{const r=await fetch(REDEEM,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({drop_id:DROP,offer_id:OFFER,session_id:sid})});const j=await r.json().catch(()=>({}));if(!r.ok){if(j.error==='sold_out')throw new Error('That Drop has just sold out.');if(j.error==='offer_ended')throw new Error('That Drop has ended.');if(j.error==='capacity_changed_try_again')throw new Error('Availability just changed. Try again.');throw new Error('Could not claim this Drop. Try again.')}code.textContent=j.redemption?.code||j.redemption?.redemption_code||'';ok.style.display='block';btn.style.display='none';if(j.capacity_remaining!==undefined)updateLeft(j.capacity_remaining);else if(!j.reused&&remaining!==null)updateLeft(Math.max(0,remaining-1));try{localStorage.setItem('perkdrop_claim_'+DROP,JSON.stringify(j.redemption||{}))}catch{}}catch(e){btn.disabled=false;btn.textContent='Claim this Drop';showError(e.message||'Could not claim this Drop.')}});document.getElementById('copy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(code.textContent||'');document.getElementById('copy').textContent='Copied'}catch{}});try{const prior=JSON.parse(localStorage.getItem('perkdrop_claim_'+DROP)||'null');if(prior?.code||prior?.redemption_code){code.textContent=prior.code||prior.redemption_code;ok.style.display='block';btn.style.display='none'}}catch{}
</script></body></html>`;
    return new Response(html,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex','X-Content-Type-Options':'nosniff'}});
  }catch(e){console.error('perkdrop-consumer-claim',e);return new Response('PerkDrop claim is temporarily unavailable.',{status:500,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})}
});
