create extension if not exists pgcrypto;

create table if not exists public.merchant_invites(id uuid primary key default gen_random_uuid(),merchant_id uuid not null references public.merchants(id) on delete cascade,email text,role text not null check(role in ('owner','admin','manager','floor','viewer')),token_hash text not null unique,created_by uuid,created_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '7 days'),accepted_at timestamptz,accepted_by uuid,revoked_at timestamptz);
alter table public.merchant_invites enable row level security; revoke all on public.merchant_invites from public,anon,authenticated; grant select,insert,update on public.merchant_invites to service_role;
create table if not exists public.partners(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,type text not null check(type in ('hotel','workplace','university','tourism','venue','creator','merchant_group','other')),status text not null default 'active' check(status in ('active','paused','archived')),market text,location text,latitude numeric,longitude numeric,contact jsonb not null default '{}'::jsonb,campaign text,notes text,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.partners enable row level security; revoke all on public.partners from public,anon,authenticated; grant select,insert,update on public.partners to service_role;
create table if not exists public.feature_flags(key text not null,environment text not null default 'production',enabled boolean not null default false,description text,updated_by text,updated_at timestamptz not null default now(),primary key(key,environment));
alter table public.feature_flags enable row level security; revoke all on public.feature_flags from public,anon,authenticated; grant select,insert,update on public.feature_flags to service_role;
create table if not exists public.marketplace_audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid,actor_email text,event_type text not null,target_type text,target_id text,before_state jsonb,after_state jsonb,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.marketplace_audit_events enable row level security; revoke all on public.marketplace_audit_events from public,anon,authenticated; grant select,insert on public.marketplace_audit_events to service_role;
create table if not exists public.provider_registry(id uuid primary key default gen_random_uuid(),name text not null unique,status text not null check(status in ('implemented','manual','experimental','not_configured','error')),capabilities jsonb not null default '{}'::jsonb,booking_url text,updated_by text,updated_at timestamptz not null default now());
alter table public.provider_registry enable row level security; revoke all on public.provider_registry from public,anon,authenticated; grant select,insert,update on public.provider_registry to service_role;
create table if not exists public.marketplace_webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,event_type text not null,received_at timestamptz not null default now(),signature_valid boolean not null default false,idempotency_key text,processing_status text not null default 'received',attempt integer not null default 1,processed_at timestamptz,error text,unique(provider,idempotency_key));
alter table public.marketplace_webhook_events enable row level security; revoke all on public.marketplace_webhook_events from public,anon,authenticated; grant select,update on public.marketplace_webhook_events to service_role;
create table if not exists public.marketplace_api_credentials(id uuid primary key default gen_random_uuid(),name text not null,token_hash text not null unique,scope_type text not null check(scope_type in ('owner','merchant','group','provider')),scope_id text,scopes jsonb not null default '[]'::jsonb,created_by uuid,created_at timestamptz not null default now(),last_used_at timestamptz,revoked_at timestamptz);
alter table public.marketplace_api_credentials enable row level security; revoke all on public.marketplace_api_credentials from public,anon,authenticated; grant select,insert,update on public.marketplace_api_credentials to service_role;
do $$ begin alter table public.merchant_pilots drop constraint if exists merchant_pilots_stage_check; alter table public.merchant_pilots add constraint merchant_pilots_stage_check check(stage in ('lead','contacted','interested','pilot_setup','live_pilot','proven','commercial_offer','paying','retained','lost')); exception when duplicate_object then null; end $$;
alter table public.merchant_pilots add column if not exists review_at timestamptz; alter table public.merchant_pilots add column if not exists next_action text; alter table public.merchant_pilots add column if not exists commercial_proposal jsonb; alter table public.merchant_pilots add column if not exists notes text; alter table public.merchant_pilots add column if not exists results jsonb;
create index if not exists merchant_invites_merchant_idx on public.merchant_invites(merchant_id,created_at desc); create index if not exists marketplace_audit_events_target_idx on public.marketplace_audit_events(target_type,target_id,created_at desc); create index if not exists webhook_events_status_idx on public.marketplace_webhook_events(processing_status,received_at desc);
